NEWS.md
descriptors/ModuleDescriptor-template.json

The interface change involves new mandatory fields but mod-inventory
only reads from the API so no code changes should be necessary.

Require `locations' interface 2.0 or 3.0 MODINV-89

---

src/test/java/api/ApiTestSuite.java
src/test/java/api/InstancesApiExamples.java
src/test/java/api/items/ItemApiCallNumberExamples.java
src/test/java/api/items/ItemApiTitleExamples.java
src/test/java/support/fakes/FakeOkapi.java
test-via-okapi.sh

* Update version of mod-inventory-storage to use to 13.1.0-SNAPSHOT
* Introduce service point properties for locations in API test preparation
* Ignore tests which break constraints around instance, holdings record and item relationships
* Change instance title searching example to use right truncation
The tests need to be replaced with isolated failure tests using fakes at a later point.

Fix tests when run via Okapi

---

ramls/instance.json
ramls/instance_context.json
ramls/inventory-batch.raml
ramls/item.json
src/test/java/api/InstancesApiExamples.java

The raml-cop was reporting validation errors on pull #116
The initial complaint was about indentation errors. As noted in the documentation, these often also mask other errors. So i have fixed various stuff -- see the individual commit messages.
There is now only one error reported: that the example is "Missing required property: errorMessages"

MODINV-119 fix raml errors

---

CODEOWNERS

To help broaden the collective ownership of this module and expand the set of folks who can review changes to this module we are introducing an initial set of code owners.
This initial set is made up of the active contributors to this module over the last year and the Tech Leads from teams actively working in this area.

Add initial set of code owners

---

src/main/java/org/folio/inventory/config/InventoryConfigurationImpl.java
src/test/java/api/InstancesApiExamples.java
src/test/java/api/support/InstanceSamples.java

Description
It is required to remove the following fields from blockable list:
0: "discoverySuppress"
1: "previouslyHeld"
2: "statusId"
3: "staffSuppress"
4: "statisticalCodeIds"
It is also required to add the following fields to the blockables list:
0: "catalogedDate"
1: "title"
2: "indexTitle"
3: "instanceTypeId"

MODINV-138 - Updated list of Instance blocked fields

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/inventory/resources/Instances.java

Libraries sometimes want to suppress records from discovery by their patrons. Much of the discovery work involves harvesting SRS MARC Bib records via OAI-PMH. When a user updates this flag in the FOLIO instance, the corresponding change should be made to the related SRS MARC Bib record, which then in turn updates the flag in the MARCcat MARC Bib record

update suppress from discovery flag in SRS on instance update (MODINV-144)

---

src/main/java/org/folio/inventory/common/Context.java
src/main/java/org/folio/inventory/common/MessagingContext.java
src/main/java/org/folio/inventory/common/WebContext.java
src/main/java/org/folio/inventory/domain/ingest/IngestMessages.java
src/main/java/org/folio/inventory/resources/AbstractInstances.java
src/main/java/org/folio/inventory/resources/Items.java
src/main/java/org/folio/inventory/resources/ingest/ModsIngestion.java
src/main/java/org/folio/inventory/support/http/client/OkapiHttpClient.java
src/test/java/api/ApiTestSuite.java
src/test/java/org/folio/inventory/storage/external/ExternalStorageSuite.java

I can't believe how many classes I had to touch for this. There should
be an "OkapiClient" that just takes context from outer request
and relay headers as necessary.. Now the Okapi headers definitions
are duplicated.

Pass X-Okapi-Request-Id MODINV-156

---

Dockerfile
descriptors/ModuleDescriptor-template.json

Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).

MODINV-175 FOLIO-2358 manage container memory

---

src/main/java/org/folio/inventory/resources/Instances.java
src/main/java/org/folio/inventory/resources/Items.java
src/test/java/api/InstancesApiExamples.java
src/test/java/api/items/ItemApiExamples.java
src/test/java/api/support/builders/ItemRequestBuilder.java
src/test/java/support/fakes/FakeOkapi.java
src/test/java/support/fakes/processors/StorageRecordPreProcessors.java
src/test/java/support/matchers/ResponseMatchers.java

https://issues.folio.org/browse/MODINV-160 - HRID handling in Inventory for Instance records.
https://issues.folio.org/browse/MODINV-162 - HRID handling in Inventory for Item records.
* Added Item/Instance fake pre-processors to generate a HRID if nothing has specified;
* Disallow changing of hrid for item and instance;
* Added unit tests.

MODINV-162, MODINV-160: Handle HRID for instance and item.

---

descriptors/ModuleDescriptor-template.json
ramls/inventory.raml
ramls/item.json
src/main/java/org/folio/inventory/domain/items/EffectiveCallNumberComponents.java
src/test/java/api/items/ItemApiExamples.java
src/test/java/api/support/builders/HoldingRequestBuilder.java
src/test/java/api/support/builders/ItemRequestBuilder.java
src/test/java/org/folio/inventory/storage/external/ExternalItemCollectionExamples.java
src/test/java/support/fakes/processors/StorageRecordPreProcessors.java

https://issues.folio.org/browse/MODINV-177: Forward effective call number typeId property.
* Forward the `effectiveCallNumberComponents.typeId` property from item;
* Update the inventory API version.
**Have to be merged after** https://github.com/folio-org/mod-inventory-storage/pull/372

MODINV-177: Forward call number type ID from item storage.

---

descriptors/ModuleDescriptor-template.json
ramls/item.json
src/main/java/org/folio/inventory/domain/items/Item.java
src/main/java/org/folio/inventory/resources/Items.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleItemCollection.java
src/test/java/api/items/ItemApiExamples.java
src/test/java/api/support/builders/ItemRequestBuilder.java

JIRA-ticket: https://issues.folio.org/browse/MODINV-190
The main purpose of this PR is to fix the problem with "lastCheckIn" field in response to the item.

MODINV-190: Most recent check in information clears when item record is edited.

---

descriptors/ModuleDescriptor-template.json

"inventory-storage.instances.batch.post" permission is missing for /inventory/instances/batch endpoint of inventory-batch 0.3 interface, which causes data-import process to fail if it is initiated by any user other than diku_admin. See [UIDATIMP-359](https://issues.folio.org/browse/UIDATIMP-359).

UIDATIMP-359 Added "inventory-storage.instances.batch.post" permission

---

descriptors/ModuleDescriptor-template.json
ramls/inventory.raml
ramls/item.json
src/main/java/org/folio/inventory/domain/items/ItemStatusName.java
src/test/java/api/ApiTestSuite.java
src/test/java/api/items/ItemAllowedStatusesSchemaTest.java
src/test/java/api/support/ApiTests.java
src/test/java/api/support/builders/ItemRequestBuilder.java

https://issues.folio.org/browse/MODINV-194: Backend: Claim returned: mark an item claim returned.
* Add `Claimed returned` to allowed item statuses list;
* Add test to verify schema enum is consistent to `org.folio.inventory.domain.items.ItemStatusName` enum.

MODINV-194: Add 'Claimed returned' to allowed item statuses list. 

---

src/main/java/org/folio/inventory/config/InventoryConfigurationImpl.java
src/test/java/api/InstancesApiExamples.java

1. "CATALOGED_DATE_KEY"-field removed from InventoryConfigurationImpl.java.
JIRA-ticket: https://issues.folio.org/browse/MODINV-202

MODINV-202: Allow editing of the Cataloged date when Instance has underlying MARC record.

---

src/main/java/org/folio/inventory/config/InventoryConfigurationImpl.java
src/test/java/api/InstancesApiExamples.java

1. "modeOfIssuanceId" was marked as a Blocked field.
2. Test fixed.

MODINV-192: Disallow editing of the Mode of issuance field when Instance has underlying MARC record.

---

descriptors/ModuleDescriptor-template.json
ramls/examples/instance_post.json
ramls/instance.json
ramls/inventory-batch.raml
ramls/inventory.raml
src/main/java/org/folio/inventory/domain/instances/Instance.java
src/main/java/org/folio/inventory/domain/instances/titles/PrecedingSucceedingTitle.java
src/main/java/org/folio/inventory/resources/AbstractInstances.java
src/main/java/org/folio/inventory/resources/Instances.java
src/main/java/org/folio/inventory/resources/InstancesBatch.java
src/main/java/org/folio/inventory/resources/InstancesResponse.java
src/main/java/org/folio/inventory/resources/InstancesResponseWrapper.java
src/test/java/api/ApiTestSuite.java
src/test/java/api/PrecedingSucceedingTitlesApiExamples.java
src/test/java/api/support/ApiTests.java
src/test/java/api/support/http/BusinessLogicInterfaceUrls.java
src/test/java/api/support/http/ResourceClient.java
src/test/java/support/fakes/FakeCQLToJSONInterpreter.java
src/test/java/support/fakes/FakeOkapi.java

https://issues.folio.org/browse/MODINV-198
- create new fields: precedingTitles and succeedingTitles in instance endpoints
- get, add, edit and delete preceding/succeeding titles using /inventory-storage/preceding-succeeding-titles endpoints

MODINV-198 Preceding titles ability to add "unconnected" and "connected" title (create, edit)

---

descriptors/ModuleDescriptor-template.json

Need to add the missing permission "inventory-storage.instances.item.get" to 
GET /inventory/instances
https://issues.folio.org/browse/MODINVSTOR-456

MODINVSTOR-456 Add the missing permission

---

src/main/java/org/folio/inventory/resources/AbstractInstances.java
src/main/java/org/folio/inventory/resources/Instances.java
src/main/java/org/folio/inventory/resources/InstancesBatch.java
src/main/java/org/folio/inventory/storage/external/CollectionResourceRepository.java
src/main/java/org/folio/inventory/validation/exceptions/UnprocessableEntityException.java
src/test/java/api/InstanceRelationshipsTest.java
src/test/java/api/support/ApiTests.java
src/test/java/api/support/fixtures/InstanceRelationshipTypeFixture.java
src/test/java/api/support/fixtures/ReferenceRecordFixture.java
src/test/java/api/support/fixtures/ReferenceRecordResponse.java
src/test/java/api/support/http/ResourceClient.java
src/test/java/api/support/http/StorageInterfaceUrls.java
src/test/java/support/fakes/EndpointFailureDescriptor.java
src/test/java/support/fakes/FakeOkapi.java
src/test/java/support/fakes/FakeStorageModule.java
src/test/java/support/fakes/FakeStorageModuleBuilder.java
src/test/java/support/fakes/processors/RecordPreProcessor.java
src/test/java/support/fakes/processors/StorageConstraintsProcessors.java
src/test/java/support/fakes/processors/StorageRecordPreProcessors.java
src/test/java/support/matchers/ResponseMatchers.java

https://issues.folio.org/browse/MODINV-215
**Purpose:**
Need to handle exception for /inventory/instances endpoints in order to understand what real happens.
**Approach:**
- add failure handle during manipulation with preceding/succeeding titles or instance relationships
- add constraint check for instance relationships and preceding-succeeding title APIs.

MODINV-215 Exception handling for /inventory/instances endpoints

---

src/main/java/org/folio/inventory/resources/Instances.java
src/test/java/api/ApiTestSuite.java
src/test/java/api/InstanceRelationshipsTest.java

https://issues.folio.org/browse/MODINV-272 - Bugfest: Inventory. Instance. Instance relationship data is not saved.
* Instance relationships had been created but was not included to the getById response (however they are included into search by query response).
* Use `instance.getParentInstances()` and `instance.getChildInstances()` instead of empty arrays.

MODINV-272: Include parent/child relationship in instance getById response

---

pom.xml
src/main/java/org/folio/inventory/resources/EventHandlers.java
src/test/java/api/events/EventHandlersApiTest.java

The mechanism for unzipping and decoding event payload was added from data-import-processing-core. 
JIRA-ticket: https://issues.folio.org/browse/MODINV-274

MODINV-274: Archive event payload

---

src/main/java/org/folio/inventory/resources/AbstractInstances.java
src/test/java/api/InstanceRelationshipsTest.java
src/test/java/api/PrecedingSucceedingTitlesApiExamples.java

https://issues.folio.org/browse/MODINV-276 - Can not set child/parent relation if the instance already has relationship.
The `createOrEdit` method was returning `new CompletedFuture<>()` when an relationship has not changed  this led that update just hangs, because the completed future was never completed.
Skip the relationships that have not been changed.

MODINV-276: Fix instance relationships update logic.

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/inventory/resources/EventHandlers.java
src/test/java/api/events/EventHandlersApiTest.java

Data import flow caused mod-inventory to crash. Investigation is ongoing, but we decided to revert the latest changes in order not to impede demo tomorrow.

Revert "MODINV-274: Archive event payload (#193)" 

---

src/main/java/org/folio/inventory/validation/ItemMarkAsWithdrawnValidators.java
src/test/java/api/items/ItemMarkWithdrawnApiTest.java

https://issues.folio.org/browse/MODINV-287 - Can't mark in process items as withdrawn.
Allow `In process` items to be marked as withdrawn.

MODINV-287: Allow In process items to be marked as withdrawn.

---

src/main/java/org/folio/inventory/config/InventoryConfigurationImpl.java
src/test/java/api/InstancesApiExamples.java

1. Preceding/Succeding titles added to the INSTANCE_BLOCKED_FIELDS.
2. Preceding/Succeding titles added to the InstancesApiExamples.

MODINV-277:Disallow editing of Preceding/Succeeding fields when Instance has an underlying MARC record

---

descriptors/ModuleDescriptor-template.json
ramls/inventory.raml
ramls/item.json
src/main/java/org/folio/inventory/domain/items/ItemStatusName.java
src/test/java/api/items/ItemAllowedStatusesSchemaTest.java
src/test/java/api/items/ItemApiExamples.java

https://issues.folio.org/browse/MODINV-291 - Add 'Lost and paid' status to allowed item statuses list.
* Add `Lost and paid` status to allowed item's statuses list;
* Update inventory API version;
* Fix some code analysis issues;

MODINV-291: Add 'Lost and paid' status to allowed item statuses list

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODINV-307 - Fix typo in mark-item-withdrawn module permission.
There was a typo in modulePermissions for the mark-withdrawn API was `inventory-storage.items.item.post` but required `inventory-storage.items.item.put`

MODINV-307: Fix typo in module permissions for mark-withdrawn API.

---

ramls/holdings-notes.json
ramls/holdings-record.json
ramls/item-notes.json
ramls/item.json
src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java

1. Notes for holdings and items moved to the separate files.

MODINV-311: Adding or changing notes in quickMARC creates error in Instance record notes [BUGFIX].

---

descriptors/ModuleDescriptor-template.json
ramls/inventory.raml
ramls/item.json
src/main/java/org/folio/inventory/domain/items/ItemStatusName.java
src/test/java/api/items/ItemApiExamples.java

https://issues.folio.org/browse/MODINV-299 - Add 'Aged to lost' status to allowed item statuses list
* Add new `Aged to lost` item status;
* Update `inventory` API version.
* Require `item-storage:8.5`

MODINV-299: Add 'Aged to lost' item status.

---

src/main/java/org/folio/inventory/support/http/server/JsonResponse.java
src/test/java/api/holdings/HoldingsApiMoveExamples.java
src/test/java/api/items/ItemApiMoveExamples.java

Fix for http status code mismatching [MODINV-329](https://issues.folio.org/browse/MODINV-329).

MODINV-329 - Move: endpoints invalid status code

---

pom.xml

Upgrades to log4j 2 and switches to using a bill of materials instead of manually changing each version.
Also upgrades Guava to 29 as there was another security alert for that.

Upgrade to log4j 2 MODINV-197

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODINV-164 - Missing module permission in GET "/inventory/instances".
Use correct instance-relationships API permissions for:
* Get an instance by id;
* get instances by query.
* put/post instances;
* batch create instances.

MODINV-164: Fix instance relationships permissions.

---

pom.xml
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateHoldingEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandler.java
src/main/java/org/folio/inventory/resources/EventHandlers.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingsRecordCollection.java

https://issues.folio.org/browse/MODINV-335 - Upgrade to JDK 11
Upgrade RMB based folio libs, that is suggested by @KaterynaSenchenko in the jira comment.

MODINV-335: Update folio-libs versions that uses RMB.

---

descriptors/ModuleDescriptor-template.json
ramls/instance.json
ramls/item.json
src/main/java/org/folio/inventory/domain/instances/Instance.java
src/main/java/org/folio/inventory/domain/items/ItemStatusName.java
src/main/java/org/folio/inventory/resources/AbstractInstances.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleInstanceCollection.java

- propagate Instance.matchKey
- propagate Item.status enumeration option "Unknown"
- requires new minor versions of instance-storage, item-storage

Propagate storage data elements to support Inventory as shared index

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODINV-120 - User cannot manage records with mod-inventory permissions only

MODINV-120: Add missing inventory/items permissions.

---

pom.xml

Upgrade junit version from 4.12 to 4.13.1.
References:
https://github.com/junit-team/junit4/security/advisories/GHSA-269g-pwp5-87pp
https://nvd.nist.gov/vuln/detail/CVE-2020-15250

MODINV-353: JUnit 4.13.1 fixing TemporaryFolder information disclosure

---

src/main/java/org/folio/inventory/domain/items/Item.java
src/test/java/api/items/MarkItemMissingApiTests.java

This fixes the issue: when item is marked missing, its circulation notes were not populated.
Jira: https://issues.folio.org/browse/MODINV-355

MODINV-355: Marking item missing clears check in note and check out note fields

---

src/main/java/org/folio/inventory/validation/MarkAsWithdrawnValidators.java
src/test/java/api/items/MarkItemWithdrawnApiTests.java

The module has a "whitelist" of statuses from which an item can be moved
to withdrawn.  "Lost and Paid" was not on that list, hence the error.  I
just added the status to the list.
refs: https://issues.folio.org/browse/MODINV-369

MODINV-369: Item with Lost and paid status throws an error when withdrawn

---

ramls/holdings-record.json
src/main/java/org/folio/inventory/resources/MoveApi.java
src/test/java/api/items/ItemApiMoveExamples.java

[MODINV-378](https://issues.folio.org/browse/MODINV-378) - Item moving error
**Purpose**
The new field _version (https://github.com/folio-org/mod-inventory-storage/blob/bc8814fd8859508e5da061961cd36d5ee8f89e20/ramls/holdingsrecord.json#L11) was introduced in scope of story [MODINVSTOR-656](https://issues.folio.org/browse/MODINVSTOR-656). This affect items moving flow with error 500 - Can`t map json to 'Holdingsrecord' entity.
**Approach**
Change from getHoldingsRecordCollection to getHoldingCollection.

MODINV-378 - Item moving error

---

descriptors/ModuleDescriptor-template.json
ramls/inventory-event-handlers.raml

After refactoring of data-import flow to go directly through kafka **_/inventory/handlers/data-import_** endpoint has been removed. 'inventory-event-handlers' API version is bumped to reflect that change.

Update inventory-event-handlers API

---

descriptors/ModuleDescriptor-template.json
ramls/inventory.raml

The inventory interface needs to be updated because of adding of contributorsNames index in mod-inventory-storage
Please see https://issues.folio.org/browse/MODINV-390 and its related tickets.

Update inventory from 10.9 to 10.10

---

pom.xml

Update the `kafka-wrapper` dependency to a release version rather than pre-release, in order for it to be releasable.
Also update the `pubsub-client` dependency as that is produced by the same release process.

Update kafka wrapper dependency MODINV-373

---

src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
src/main/java/org/folio/inventory/dataimport/consumers/MarcBibInstanceHridSetKafkaHandler.java

to facilitate tracing of processing flow of a particular record
* correlationId is set to payload context before handling to be published with result event using di-core library (https://github.com/folio-org/data-import-processing-core/pull/138)
* correlationId is logged from a kafka event header
[MODSOURMAN-437](https://issues.folio.org/browse/MODSOURMAN-437)

Add logging for event correlationId

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateInstanceEventHandler.java
src/test/java/org/folio/inventory/eventhandlers/UpdateInstanceEventHandlerUnitTest.java

Instances in Inventory are not updated with the appropriate user name when the source record is updated via QM
Populate user ID and okapi token to context from event. After this change mod-inventory will call mod-inventory-storage with headers that describe real user instead of pub-sub user

MODINV-399 Support USER_CONTEXT in handling qm-update event

---

pom.xml
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/AbstractLoader.java

to process `###REMOVE###` expression for `StringValue` while updating entities (instance, holdings, item) using data-import
* correct errors logging
* update dependency on di-core library
[MODINV-404](https://issues.folio.org/browse/MODINV-404)
[MODDICORE-137](https://issues.folio.org/browse/MODDICORE-137)

MODINV-404 - Item update failed

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/InstanceUpdateDelegate.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
src/main/java/org/folio/inventory/domain/instances/Instance.java
src/main/java/org/folio/inventory/resources/AbstractInstances.java
src/main/java/org/folio/inventory/resources/Instances.java
src/main/java/org/folio/inventory/resources/InstancesBatch.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleInstanceCollection.java
src/main/java/org/folio/inventory/support/InstanceUtil.java
src/test/java/org/folio/inventory/dataimport/consumers/MarcBibInstanceHridSetKafkaHandlerTest.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandlerTest.java
src/test/java/org/folio/inventory/eventhandlers/UpdateInstanceEventHandlerUnitTest.java

**Problem**
Methods for mapping from Instance JSON to Instance Java object (POJO) and from Instance POJO to Instance JSON are spread across a number of different classes with a fair amount of logic duplication too.
Some mapping methods live in ExternalStorageModuleInstanceCollection, others in AbstractInstances. It then appears that when Instance mapping was needed for either batch - processing or DI (not sure of the history), there was no (easy) way to get at the existing mapping functions in the new, separate contexts, so mapping logic was duplicated and put in InstanceUtil instead.
One problem with this is that the same mapping changes must be implemented in multiple places.
Another problem is it becomes difficult to understand where the mapping happens, and since mapping Inventory …

Modinv 403 clean up instance mapping

---

descriptors/ModuleDescriptor-template.json

[MODINV-421](https://issues.folio.org/browse/MODINV-421) - Permission error while executing GET /inventory/instances endpoint
* added missing permission

MODINV-421 - Permission error while executing GET /inventory/instances endpoint

---

src/main/java/org/folio/inventory/resources/InstancesResponse.java
src/main/java/org/folio/inventory/support/InstanceUtil.java
src/test/java/api/ApiTestSuite.java
src/test/java/api/tenant/TestTenantApiExamples.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/util/InstanceUtilTest.java

This PR was already reviewed and merged to the master, and this fix was reviewed by PO.
Reviewed PR for this: https://github.com/folio-org/mod-inventory/pull/339

MODINV-419: Instance tags should not be deleted when the instance is updated by an imported MARC record.

---

descriptors/ModuleDescriptor-template.json

Due to changes made in scope of https://issues.folio.org/browse/MODINV-410 interfaces version should be updated to notify dependant modules about changes. 
* updated requires interface version for  "source-storage-records" from 2.0 to 3.0
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

MODINV-422 - Update interface version

---

descriptors/ModuleDescriptor-template.json

Due to changes made in scope of https://issues.folio.org/browse/MODINV-410 interfaces version should be updated to notify dependant modules about changes. 
* updated requires interface version for  "source-storage-records" from 2.0 to 3.0
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

MODINV-422 - Update interface version (#348)

---

descriptors/ModuleDescriptor-template.json
ramls/instance.json
src/main/java/org/folio/inventory/domain/instances/Instance.java
src/main/java/org/folio/inventory/domain/instances/PublicationPeriod.java
src/main/java/org/folio/inventory/support/JsonHelper.java
src/test/java/api/InstancesApiExamples.java
src/test/java/org/folio/inventory/domain/instances/PublicationPeriodTest.java
src/test/java/org/folio/inventory/support/JsonHelperTest.java

Propagate the `publicationPeriod` property for instance on update/create/get.
Increase `inventory` API version to `10.12`
Require `instance-storage` of `7.8` version

MODINV-428: Propagate publicationPeriod property.

---

NEWS.md
pom.xml

As module depends upon new major (3.0) version of `source-storage-records`. This was changed during the work for [MODINV-422](https://issues.folio.org/browse/MODINV-422).

Change version to 17.0.0 MODINV-420

---

pom.xml
src/main/java/org/folio/inventory/dataimport/consumers/MarcBibInstanceHridSetKafkaHandler.java
src/test/java/org/folio/inventory/dataimport/consumers/MarcBibInstanceHridSetKafkaHandlerTest.java

Fix error updating instance after hrid has been set to srs record
https://issues.folio.org/browse/MODINV-433
* Change expected kafka event property from MARC to MARC_BIB
* Cleanup codesmells

MODINV-433 Fix error updating instance after hrid has been set to srs record

---

pom.xml

This fixes a limited path traversal vulnerability in
FileNameUtils.normalize: https://nvd.nist.gov/vuln/detail/CVE-2021-29425
Multiple mod-inventory dependencies use commons-io and might be affected.

MODINV-440: Bump commons-io from 2.4 to 2.7 (CVE-2021-29425)

---

src/main/java/org/folio/inventory/resources/Instances.java
src/test/java/api/InstancesApiExamples.java

UI side also doesn't send Id within preceding and succeeding Titles but on Back-side the service has that ID and comparing it between updating and existing data. To attain proper comparing I avoid comparing ids.

MODINV-432: zeroing proceeding succeeding Titles ids

---

NEWS.md
ramls/item.json
src/main/java/org/folio/inventory/domain/items/Item.java
src/main/java/org/folio/inventory/resources/ItemRepresentation.java
src/main/java/org/folio/inventory/resources/Items.java
src/test/java/api/BoundWithTests.java

For Items that are bound-withs, the Inventory UI needs to display the list of titles that are bound together within the Item - in the Item details view.
This change is meant to assist the UI rendering logic by providing the required information in the Item itself.  See the mock-up in UIIN-1545 for the fields to be shown. 
The suggested solution is to embed the list of titles in the Item. This is similar to how a single Instance title is embedded in the Item representation for a non-bound-with Item.  
The information needed is:  instance.title, instance.id (for linking), instance.hrid, holdingsRecord.id (for linking) and holdingsRecord.hrid.  More properties could be added later if necessary. 
Since there's no current need for this information to be present in Items of a result set, the …

Modinv 443 bound with in item by

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java

Inventory created more Instances records than were in the file because it generates a unique id for each request
In our distributed system, we can use the unique id already created by another module, since these entities are in the 1-2-1 relationship
https://issues.folio.org/browse/MODINV-455

MODINV-455: Inventory created more Instances records than were in the file

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/PrecedingSucceedingTitlesHelper.java
src/main/java/org/folio/inventory/resources/AbstractInstances.java
src/main/java/org/folio/inventory/resources/Instances.java
src/main/java/org/folio/inventory/resources/Items.java
src/main/java/org/folio/inventory/resources/ItemsByHoldingsRecordId.java
src/main/java/org/folio/inventory/storage/external/CollectionResourceClient.java
src/main/java/org/folio/inventory/storage/external/CollectionResourceRepository.java
src/main/java/org/folio/inventory/storage/external/CqlQuery.java
src/main/java/org/folio/inventory/storage/external/MultipleRecordsFetchClient.java
src/main/java/org/folio/inventory/storage/external/ReferenceRecordClient.java
src/main/java/org/folio/inventory/support/CqlHelper.java
src/test/java/api/InstanceRelationshipsTest.java
src/test/java/org/folio/inventory/storage/external/CqlQueryTest.java

When retrieving a single instance by ID,  the default RMB limit of 10 records has been in effect and ui-inventory, for example, could thus only display the first 10 parent and/or child relationships of an instance. 
With this PR this limitation would be removed. 
When retrieving multiple instances by query, there was already no such limit or parents/children of each instance in the result set.
The same issue is fixed for precedingSucceedingTitles.
A new getAll method is used for this.
The getMany without limit/offset parameters is no longer in use and is deleted.
The urlEncoding and cqlEncoding is fixed - for separation of concerns:
* When building a CQL query do cqlEncoding. For example in CqlQuery.
* When building a URL do urlEncoding.
CQL encoding and URL encoding is moved to the …

Remove limit of 10 parents/children in single instance (MODINV-446)

---

pom.xml
src/main/java/org/folio/inventory/DataImportConsumerVerticle.java
src/main/java/org/folio/inventory/Launcher.java
src/main/java/org/folio/inventory/MarcBibInstanceHridSetConsumerVerticle.java
src/main/java/org/folio/inventory/QuickMarcConsumerVerticle.java
src/main/java/org/folio/inventory/dataimport/util/KafkaConfigConstants.java
src/test/java/org/folio/inventory/dataimport/consumers/DataImportConsumerVerticleTest.java
src/test/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandlerTest.java
src/test/java/org/folio/inventory/dataimport/consumers/MarcBibInstanceHridSetConsumerVerticleTest.java
src/test/java/org/folio/inventory/quickmarc/consumers/QuickMarcConsumerVerticleTest.java
src/test/java/org/folio/inventory/quickmarc/consumers/QuickMarcKafkaHandlerTest.java

https://issues.folio.org/browse/MODINV-466
https://issues.folio.org/browse/MODPUBSUB-187
When attempting to import a file the import job does not complete due to the following error
org.apache.kafka.common.errors.RecordTooLargeException: The message is 1287037 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.
Update to folio-kafka-wrapper v2.3.2 allows to set max.request.size parameter
https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#producerconfigs_max.request.size

MODINV-466 Support max.request.size configuration

---

src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingsRecordCollection.java

During the investigation on MODDATAIMP-496 such a message was observed in the mod-inventory-storage log on holdings record update through data-import
> 14:27:58 [] [] [] [] WARN  ?                    Backend notice: severity='NOTICE', code='23F09', message='Ignoring optimistic locking conflict while overwriting changed record fbad6996-f827-498c-8512-92e10e9f8c6b: Stored _version is 1, _version of request is <NULL>', detail='null', hint='null', position='null', internalPosition='null', internalQuery='null', where='PL/pgSQL function holdings_record_set_ol_version() line 8 at RAISE', file='pl_exec.c', line='3862', routine='exec_stmt_raise', schema='diku_mod_inventory_storage', table='holdings_record', column='null', dataType='null', constraint='null' …

MODINV-471 - Ensure version property while updating holdings record using the data-import

---

pom.xml
src/main/java/org/folio/inventory/parsing/ModsParser.java
src/test/java/org/folio/inventory/TestUtil.java

Removing the commons-io dependency reduces the attack surface of the module and makes the life of the FOLIO security group easier.

MODINV-441 Remove commons-io dependency

---

pom.xml

Steps to Reproduce:
* Open mod-inventory in Eclipse
Expected Results: Compiles
Actual Results: Compile error "The package org.xml.sax is accessible from more than one module: `<unnamed>`, `java.xml`"
Additional Information:
https://stackoverflow.com/questions/55571046/eclipse-is-confused-by-imports-accessible-from-more-than-one-module
This pull request fixes a clear violation of the Java specs. The compiler used by Eclipse is not as lenient as the compiler used by maven.

MODINV-450: org.xml.sax is accessible from more than one module (xerces:xmlParserAPIs)

---

src/main/java/org/folio/inventory/DataImportConsumerVerticle.java
src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateHoldingEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateMarcHoldingsEventHandler.java
src/main/java/org/folio/inventory/dataimport/util/ParsedRecordUtil.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateHoldingEventHandlerTest.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateMarcHoldingsEventHandlerTest.java
src/test/resources/handlers/marc-holdings-rules.json
src/test/resources/marc/parsed-holdings-record.json

We need to make mod-inventory to generate Holdings from incoming SRS Marc Holdings
- created handler for populating instance id and storing holdings in the mod-inventory-storage
- throws DI_INVENTORY_HOLDINGS_CREATED_READY_FOR_POST_PROCESSING, prepare event payload for post-processing
- generated Holdings using the corresponding Processor from data-import-processing-core
https://issues.folio.org/browse/MODINV-483

MODINV-483 Generate Holdings from Marc Holdings

---

pom.xml

folio-kafka-wrapper v2.4.0 was released, the development version 2.4.0-SNAPSHOT is no longer relevant and will be deleted from nexus repository

Update folio-kafka-wrapper to v2.4.0

---

pom.xml

data-import-processing-core v3.2.0 was released, the development version 3.2.0-SNAPSHOT is no longer relevant and will be deleted from nexus repository

Update data-import-processing-core to v3.2.0

---

ramls/authority.json
ramls/samples/authority.sample

**_Purpose_**
The purpose is to update the schema accordingly to the mapping rules created in https://github.com/folio-org/mod-source-record-manager/pull/505/files
There is a need to simplify the schema to do not have complex objects (object with multiple fields) because the mapping processor can't seem to handle such mapping

MODINV-504 - Updated authority schema according to the new mapping rules

---

ramls/authority.json

**_Purpose_**
This update is missing in a previous PR https://github.com/folio-org/mod-inventory/pull/407
This 'genre' field needs to be updated similarly to other fields. 
The related sample file is already updated.

MODINV-504 - updated 'genre' field

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateMarcHoldingsEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateMarcHoldingsEventHandlerTest.java

Inventory created more holdings records than were in the file because it generates a unique id for each request
In our distributed system, we can use the unique id already created by another module, since these entities are in the 1-2-1 relationship
https://issues.folio.org/browse/MODINV-564

MODINV-564 Import of MARC Holdings might create more Holdings than were in the file (kiwi bugfix)

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/handlers/matching/AbstractMatchEventHandler.java

Cannot match HOLDINGS via locations.
Fixed put for mappingParams into dataImportEventPayload context
[MODINV-571](https://issues.folio.org/browse/MODINV-571)

MODINV-571 Fixed put for mappingParams into dataImportEventPayload

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateMarcAuthorityEventHandler.java

Uncomment line which sets the source for MARC Authority record when [MODINVSTOR-825](https://issues.folio.org/browse/MODINVSTOR-825) ready

MODINV-576 Uncomment line to set source field for MARC Authority

---

src/main/java/org/folio/inventory/dataimport/exceptions/DataImportException.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/AuthorityUpdateDelegate.java
src/test/java/org/folio/inventory/quickmarc/consumers/QuickMarcKafkaHandlerTest.java
src/test/resources/handlers/authority-record.json

Fix quickMarc Authority update
- AuthorityUpdateDelegate should use authorityId to get existing record from inventory-storage
- AuthorityUpdateDelegate should return an error if inventory-storage returns 404 status

MODINV-596 Fix quickMarc Authority update

---

NEWS.md
pom.xml

Resolve CVE-2021-44228 as per [MODINV-599](https://issues.folio.org/browse/MODINV-599).
Use 2.16.0 rather than 2.15.0, it contains additional changes related to the CVE and is also the version RMB is set to use as of [Release 33.1.3](https://github.com/folio-org/raml-module-builder/pull/1002).

MODINV-599: Update Log4j to 2.16.0.

---

NEWS.md
pom.xml

Resolve CVE-2021-44228 as per [MODINV-599](https://issues.folio.org/browse/MODINV-599) for 18.0 version (Used by Kiwi).
Use 2.16.0 rather than 2.15.0, it contains additional changes related to the CVE and is also the version RMB is set to use as of [Release 33.1.3](https://github.com/folio-org/raml-module-builder/pull/1002).

MODINV-599: Update Log4j to 2.16.0 (Kiwi R3 2021).

---

NEWS.md
pom.xml

Resolve CVE-2021-44228 as per [MODINV-601](https://issues.folio.org/browse/MODINV-601).

MODINV-601: Update Log4j to 2.16.0 (Juniper R2 2021).

---

NEWS.md
src/main/java/org/folio/inventory/QuickMarcConsumerVerticle.java
src/main/java/org/folio/inventory/dataimport/consumers/QuickMarcKafkaHandler.java
src/test/java/org/folio/inventory/quickmarc/consumers/QuickMarcKafkaHandlerTest.java

Kafka Cache is used in QuickMarcKafkaHandler in mod-inventory. Just remove Kafka cache (consumer receiving QM_COMPLETED supports deduplication).
[MODINV-614](https://issues.folio.org/browse/MODINV-614)

MODINV-614 Remove Kafka cache for QuickMarcKafkaHandler

---

src/main/java/org/folio/inventory/DataImportConsumerVerticle.java
src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
src/test/java/org/folio/inventory/dataimport/consumers/DataImportConsumerVerticleTest.java
src/test/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandlerTest.java

to remove Kafka cache from DataImportKafkaHandler since events deduplication relies on uniqueness constraint of entities IDs  during entities creation
* remove Kafka cache from DataImportKafkaHandler
[MODINV-603](https://issues.folio.org/browse/MODINV-603)

MODINV-603 - Remove Kafka cache by handling Constraint Violation Exceptions for DataImportKafkaHandler

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/inventory/common/dao/PostgresConnectionOptions.java
src/test/java/org/folio/inventory/dao/PostgresClientFactoryTest.java

Idle timeout time units defaults - seconds, and this PR fixes setting of idle timeout for mod-inventory DB that is equals to 60 sec now.
It can prevent potential issues when closed connection remains in pool

Fix timeunits for setting Idle timeout

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/AbstractAuthorityEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateAuthorityEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateAuthorityEventHandlerTest.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandlerTest.java

Create/update Authority handlers should send post-processing events:
DI_INVENTORY_AUTHORITY_CREATED_READY_FOR_POST_PROCESSING
DI_INVENTORY_AUTHORITY_UPDATED_READY_FOR_POST_PROCESSING
[MODINV-628](https://issues.folio.org/browse/MODINV-628)

MODINV-628 Send post-processing event from create/update Authority handlers

---

src/test/java/org/folio/inventory/storage/external/failure/ExternalStorageFailureSuite.java

*Purpose*
The `ExternalAuthorityCollectionServerErrorExamples` rely on state / preparation from the `ExternalStorageFailureSuite`. This means they need to run within that suite to be reliably executed. Running outside the suite can lead to failures depending upon the combination / order of tests executed.

Include server error failure tests in suite MODINV-501

---

pom.xml

mod-inventory requires org.postgresql:postgresql for liquibase.
The version org.postgresql:postgresql:42.2.23 has a remote code execution vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2022-21724
https://jdbc.postgresql.org/download.html#current advises to switch to 42.3.*.
42.3.2 fixes the vulnerability.

MODINV-634: PostgreSQL JDBC 42.3.2 Security update (CVE-2022-21724)

---

src/test/java/api/ApiTestSuite.java
src/test/java/api/InventoryConfigApiTest.java

The `InventoryConfigApiTest`s rely on state / preparation from the `ApiTestSuite`. This means they need to run within that suite to be reliably executed. Running outside the suite can lead to failures depending upon the combination / order of tests executed.

Include config API tests in suite MODINV-498

---

pom.xml

New 2.4.2 version of Vertx recenly released.
https://github.com/vert-x3/wiki/wiki/4.2.4-Release-Notes#vertx
It contains fixes related to the connection pool and other issues.
So expected version in module pom:
Vertx - 2.4.2

MODINV-643. Upgrade Vertx versions that contain fixes for the connection pool

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandlerTest.java

**Overview**: The main issue of this ticket is that in cases when there is an update just only for Item-entity -> there is no information about an instance in UI. That's why hotlinks for "UPDATED" Item don't work.
**Approach**: 
If there is no data about Holding in the context at the ItemUpdateHandler, then the new code will go and retrieve a Holding by id (it exists in Item-entity). After that, this Holding(with instanceId) will be added to the payload for the build of all needed data for UI in the next steps of data-import.

MODINV-641: Can't provide instanceId to build hotlink for Item when trying to update Item and match by Item's field

---

pom.xml

Upgrade RMB and Vertx versions that contain fixes for the connection pool
https://issues.folio.org/browse/MODINV-648

MODINV-648: Upgrade Vertx to 4.2.5

---

src/main/java/org/folio/inventory/common/VertxAssistant.java
src/main/java/org/folio/inventory/support/http/client/OkapiHttpClient.java
src/test/java/api/ApiTestSuite.java
src/test/java/org/folio/inventory/storage/external/ExternalStorageSuite.java
src/test/java/org/folio/inventory/support/http/client/OkapiHttpClientTests.java

This is a test-only fix. There seem to be no problem with
main usage of clients as various Verticle implementations
create one HttpClient. However, the code could be further be
simpfified by not createing them at all.. Just pass Vertx
which is already there in many cases. And let OkapiHttpClient
worry about WebClient creation.

Fewer sockets in use for tests MODINV-650

---

src/main/java/org/folio/inventory/DataImportConsumerVerticle.java
src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/DeleteAuthorityEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/DeleteAuthorityEventHandlerTest.java

The module should be able to process the DI_SRS_MARC_AUTHORITY_RECORD_DELETED event.
Subscribe to DI_SRS_MARC_AUTHORITY_RECORD_DELETED topic
Create a handler for Authority delete action that will delete Authority from mod-inventory-storage
[MODINV-635](https://issues.folio.org/browse/MODINV-635)

MODINV-635 Create processor for Delete Authority record

---

src/main/java/org/folio/inventory/Launcher.java

Even though Kafka message payload was significantly decreased, it is still recommended to adjust MAX_REQUEST_SIZE value to allow importing large files. Setting default value to 4000000 bytes would make adjustment of that property unnecessary.

Adjust default max_request_size value for kafka messages

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/AbstractLoader.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/AuthorityLoader.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/HoldingLoader.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/InstanceLoader.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/ItemLoader.java
src/test/java/org/folio/inventory/eventhandlers/MatchAuthorityEventHandlerUnitTest.java
src/test/java/org/folio/inventory/eventhandlers/MatchHoldingEventHandlerUnitTest.java
src/test/java/org/folio/inventory/eventhandlers/MatchInstanceEventHandlerUnitTest.java
src/test/java/org/folio/inventory/eventhandlers/MatchItemEventHandlerUnitTest.java

Previously an error should be propagated when multiple inventory entities (instance etc) are matched.
Currently, it's necessary to process multiple match results by next sub-match profile if such exists
* check whether current match profile contains a sub-match profile that linked for matches and populate matching result for further processing
* provide logic for entities loaders to process multiple matching results from the previous matching
* add tests
[MODINV-652](https://issues.folio.org/browse/MODINV-652)

MODDICORE-247 - Record matches are not decreased when additional match conditions are added to a job profile

---

src/main/java/org/folio/inventory/common/api/request/PagingParameters.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/AbstractLoader.java

It is necessary to expand the limit for records loading during a match profile processing. Currently a default limit value is used limit=10, that may not be enough for further processing multiple matching results by next linked match profile
[MODINV-652](https://issues.folio.org/browse/MODINV-652)

MODINV-652 - Record matches are not decreased when additional match conditions are added to a job profile

---

src/main/java/org/folio/inventory/Launcher.java

Added a field to initialize Kafka consumer from the environment variable.
If the field value is not initialized by default, it will execute as it was executing earlier.

MODINV-658 - Kafka consumer initialization changes

---

src/main/java/org/folio/inventory/services/HoldingsCollectionService.java

Fix latency in create holdings flow
`hrid` field is indexed with btree. To speed up search by `hrid` operator `==` should be used in cql query

MODINV-669 Fix latency in create holdings flow

---

NEWS.md
descriptors/ModuleDescriptor-template.json

Investigation showed the search was hanging because it could
not complete a lookup to the item-storage endpoint for bound-with 
holdings. I added that permission to the relevant endpoint.

MODINV-662: Fetching instance fails to respond with minimal permissions

---

src/main/java/org/folio/inventory/support/InstanceUtil.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/util/InstanceUtilTest.java

1. Added "administrativeNotes" to the existing mechanism.
2. Test added.

MODINV-679: Updating an instance with data import erases administrative note

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/handlers/matching/preloaders/OrdersPreloaderHelper.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/preloaders/PreloadingFields.java
src/main/java/org/folio/inventory/support/CqlHelper.java
src/test/java/org/folio/inventory/eventhandlers/preloaders/OrdersPreloaderHelperTest.java
src/test/java/org/folio/inventory/support/CqlHelperTest.java

To implement the matching logic invoked when a user selects Vendor reference number (VRN) as the matchpoint from an incoming MARC Bibliographic record to an existing Inventory Instance, Holdings, or Item
- add preloading field
- extend OrdersPreloaderHelper to support VRN matches
- implement unit tests
[MODINV-577](https://issues.folio.org/browse/MODINV-577)

MODINV-577 Match logic for VRN matches to Inventory records

---

src/main/java/org/folio/inventory/support/InstanceUtil.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/util/InstanceUtilTest.java

OL field "_version" is mandatory only for cases when OL is enabled.
Added a condition to check this case
[MODINV-684](https://issues.folio.org/browse/MODINV-684)

MODINV-684: Fix "_version" is not mandatory field

---

pom.xml

Upgrade liquibase-core from 4.6.2 to 4.9.1 fixing XML External Entity (XXE) Injection: https://nvd.nist.gov/vuln/detail/CVE-2022-0839
Upgrade httpclient from 4.5.2 to 4.5.13 fixing Improper Input Validation: https://nvd.nist.gov/vuln/detail/CVE-2020-13956
Upgrade guava from 29.0 to 31.1 fixing false positive report about Information Disclosure: https://nvd.nist.gov/vuln/detail/CVE-2020-8908
Upgrade log4j from 2.17.0 to 2.17.2 fixing false positive report about Arbitrary Code Execution: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832

MODINV-692: Upgrade dependencies (CVE-2022-0839, CVE-2020-13956)

---

src/main/java/org/folio/inventory/resources/Instances.java
src/main/java/org/folio/inventory/resources/Items.java

The cause of this problem was that the instance retrieval code that sets the 
bound-with flag does not check to see if holdings records attached to
the instance record actually have items before doing an item record lookup.
This results in it sending an empty list to the code in items that fills out the 
item records, which also has no guard to see if it's actually being passed 
item records.  The item endpoint therefore tries to look up non-existent 
records.  Most of the code just passes over the empty records, but the 
bound-with lookup actually inserts an empty value into the bound-with 
endpoint lookup, resulting in a cql query error.  
I put two guards in place to address this.  One is in the instance code that 
does the bound-with lookup, and checks to make sure there are item …

MODINV-550: Bound-with-parts gets an empty collection

---

src/main/java/org/folio/inventory/support/InstanceUtil.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/util/InstanceUtilTest.java

Before merging existing and maped instances (one of step preparation before mapping) we didn't map status updated date. As result it was overwriten in the instance replace operation where we don't set Instance status term in mapping profile.
[MODINV-715](https://issues.folio.org/browse/MODINV-715)

MODINV-715 Update instance import overwrites the update date for instance status when profile is not editing the instance status

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandlerTest.java

**_Purpose_**
https://issues.folio.org/browse/MODINV-705
Updating "MARC Authority" record by matching "999 ff $s" subfield fails with "Completed with errors" status and MARC record doesn't update.
**_Approach_**
The approach is to set a 'relatedRecordVersion' to the target updating record, this prevents Optimistic Locking error on update

MODINV-705 Updating "MARC Authority" record causes errors

---

src/main/java/org/folio/inventory/dataimport/handlers/matching/AbstractMatchEventHandler.java
src/test/java/org/folio/inventory/eventhandlers/MatchInstanceEventHandlerUnitTest.java

it should be possible to save errors to the data import journal due to infrastructure failure during event processing for entities matching. For instance, such error can occur on getting mapping metadata.
* set corresponding event type to dataImportEventPayload before processing in the AbstractMatchEventHandler handler to make it processable by journal handler
* add test
[MODINV-723](https://issues.folio.org/browse/MODINV-723)

MODINV-723 - Pre-set event type to payload before processing event for entities matching

---

NEWS.md
descriptors/ModuleDescriptor-template.json
ramls/instance.json
ramls/inventory.raml
src/main/java/org/folio/inventory/domain/ingest/IngestMessageProcessor.java
src/main/java/org/folio/inventory/domain/instances/Contributor.java
src/main/java/org/folio/inventory/domain/instances/Instance.java
src/test/java/api/support/InstanceSamples.java
src/test/java/org/folio/inventory/storage/external/ExternalInstanceCollectionExamples.java

It's needed to have information if a contributor is controlled by authority
Extend instance.contributors with authorityId

MODINV-729 Extend instance contributors schema with Authority ID

---

NEWS.md
descriptors/ModuleDescriptor-template.json
ramls/inventory.raml
src/main/java/org/folio/inventory/common/FutureAssistance.java
src/main/java/org/folio/inventory/domain/AsynchronousCollection.java
src/main/java/org/folio/inventory/resources/Instances.java
src/main/java/org/folio/inventory/resources/Items.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleCollection.java
src/main/java/org/folio/inventory/storage/memory/InMemoryIngestJobCollection.java
src/test/java/api/InstancesApiExamples.java
src/test/java/api/TenantApiTest.java
src/test/java/api/support/Preparation.java
src/test/java/api/support/http/ResourceClient.java
src/test/java/org/folio/inventory/storage/external/ExternalInstanceCollectionExamples.java
src/test/java/org/folio/inventory/storage/memory/InMemoryIngestJobCollectionExamples.java
src/test/java/support/fakes/FakeStorageModule.java

mod-inventory-storage has changed the DELETE all records API for instances, holdings and items. It requires a query parameter with the CQL query that selects the records to delete.
mod-inventory should also require this query parameter and pass it to mod-inventory-storage APIs.

MODINV-731: Delete instance/item by CQL

---

pom.xml

Upgrade postgresql from 42.3.3 to 42.5.0 fixing SQL Injection https://nvd.nist.gov/vuln/detail/CVE-2022-31197
Upgrade mod-source-record-storage-client from 5.3.0 to 5.4.1, this upgrades jackson-databind from 2.13.1 to 2.13.2.1 fixing Denial of Service (DoS) https://nvd.nist.gov/vuln/detail/CVE-2020-36518
Upgrade Vert.x from 4.2.6 to 4.3.3, this upgrades vertx-kafka-client from 4.2.6 to 4.3.3, this upgrades jackson-databind from 2.13.1 to 2.13.2.20220324 fixing Denial of Service (DoS) https://nvd.nist.gov/vuln/detail/CVE-2020-36518

MODINV-732: PostgreSQL 42.5.0, jackson-databind 2.13.2.1, Vert.x 4.3.3

---

NEWS.md
pom.xml

The module major version should have been changed during the breaking compatibility changes in MODINV-731.

Increment major version due to breaking changes MODINV-731

---

Jenkinsfile
README.MD
ramls/inventory-config.raml
ramls/inventory.raml

The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
The https://dev.folio.org/reference/api/#mod-inventory section of API documentation will be automatically reconfigured:
https://dev.folio.org/reference/api/#explain-gather-config

FOLIO-3231 Use new api-lint and api-doc CI facilities

---

README.MD
src/main/java/org/folio/inventory/Launcher.java
src/main/java/org/folio/inventory/MarcBibUpdateConsumerVerticle.java
src/main/java/org/folio/inventory/dataimport/cache/MappingMetadataCache.java
src/main/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandler.java
src/main/java/org/folio/inventory/domain/dto/InstanceEvent.java
src/test/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateConsumerVerticleTest.java
src/test/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandlerTest.java

Link update: Update instance according to srs.bib event
1. Introduce a new verticle that will init consumer for `srs.marc-bib` topic
2. Register verticle in `Launcher`
3. Introduce a handler for a consumer. It should:
- Retrieve mapping rules and mapping parameters for marc-bib (GET /mapping-metadata/type/marc-bib)
- Use local cache to store mapping metadata (MappingMetadataCache), use jobId from message
- Use InstanceUpdateDelegate to update instance record in mod-inventory-storage
https://issues.folio.org/browse/MODINV-748

MODINV-748 - Link update: Update instance according to srs.bib event

---

src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateMarcHoldingsEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateMarcHoldingsEventHandlerTest.java

_MARC-to-MARC Holdings update stacked_
There were two reasons (in **UpdateMarcHoldingsEventHandler** class):
1) Incorrect holdingsId set when parsing payload into Holdings object, for this reason, it was not possible to load proper holding from inventory storage
2) After fixing first problem, we try to update holding sending PUT request to mod-inventory-storage, but required field instanceId was missing in the request body. The main root cause was incorrect chain used in completion stage, so two thenAccept methods were used which one was responsible to find and fill instanceId by hrid, second was responsible to send holding to mod-inventory-storage to update.
To resolve above issues:
1) holdingsId extracted from marcRecord using getExternalIdsHolder().getHoldingsId() method and set to …

MODINV-760 - MARC-to-MARC Holdings update stacked

---

descriptors/ModuleDescriptor-template.json

[CIRCSTORE-353](https://issues.folio.org/browse/CIRCSTORE-353) introduced a breaking change by making request status a required property. Update versions of interfaces impacted by this change.
Resolves [MODINV-767](https://issues.folio.org/browse/MODINV-767)

MODINV-767: Update version of request-storage

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateMarcHoldingsEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateMarcHoldingsEventHandlerTest.java

_Event not published during MARC-to-MARC Holdings update_
After updating holding, request was constantly sending to mod-inventory-storage 
To resolve above issue:
Published copied payload without current node
https://issues.folio.org/browse/MODINV-770

MODINV-770 - Event not published during MARC-to-MARC Holdings update

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandler.java
src/main/resources/log4j2-json.properties
src/main/resources/log4j2.properties

https://issues.folio.org/browse/MODDATAIMP-758HAide SQL requests (org.folio.rest.persist.PostgresClient) from log files for the next modules:
mod-data-import
mod-source-record-storage
mod-data-import-converter-storage
mod-inventory-storage
This class logs SQL queries at the INFO level, which leads to a very large size of log files.
SRS: a lot of messages like this:
2023-01-05 09:28:12.246 WARN AbstractConfig The configuration 'ssl.protocol' was supplied but isn't a known config.
....
2023-01-05 09:28:12.246 WARN AbstractConfig The configuration 'ssl.truststore.type' was supplied but isn't a known config.
SRM: move to TRACE level or decrease defaultRules json
2023-01-05 01:55:50.850 [vert.x-eventloop-thread-1] [572525/proxy;692150/tenant] [diku] [] [mod_source_record_manager] DEBUG …

[MODDATAIMP-758]Imrove logging (hide SQL requests)

---

src/main/java/org/folio/inventory/domain/dto/InstanceEvent.java
src/test/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandlerTest.java

Update schema to fix parsing exception
- add `linkIds` field to schema
[MODINV-773](https://issues.folio.org/browse/MODINV-773)

MODINV-773 Controlled Instance's field doesn't reflect the updates made by user in MARC Authority's 1XX

---

src/main/java/org/folio/inventory/Launcher.java

Add a warning block to the log when the module starts without consumers
Added a warning block to the log when the module starts without consumers

[MODINV-711] Add a warning block to the log when the module starts without consumers

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
Jenkinsfile
README.MD
ramls/inventory.raml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MODINV-812 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

.github/workflows/macos.yml
Dockerfile
Jenkinsfile
NEWS.md
pom.xml

**Purpose:** Upgrade mod-inventory to Java 17.
**Description:** updated folio-isbn-util, folio-kafka-wrapper dependencies with snapshot versions for the sake of testing since these modules also were migrated to Java 17

MODINV-826: Upgrade mod-inventory to Java 17

---

ramls/inventory.raml
src/main/java/org/folio/inventory/resources/ItemsByHoldingsRecordId.java
src/test/java/api/BoundWithTests.java

This API causes significant problems for mod-inventory and UI Inventory when dealing with holdings records with extremely many (12000+) items. 
The PR would set a default page size of 200 items and a maximum page size of 10000 items. 
The PR also simplifies some bound-with logic that was more complicated than necessary, thus improving performance some.

Support paging in /items-by-holdings-id API (MODINV-838)

---

src/main/java/org/folio/inventory/resources/Instances.java
src/main/java/org/folio/inventory/validation/InstanceSourceTypeValidator.java
src/test/java/api/InstancesApiExamples.java
src/test/java/api/support/InstanceSamples.java
src/test/java/api/support/builders/InstanceRequestBuilder.java

Shadow Instances are instances that live in a local tenant and share corresponding identifier with another instance in the central tenant of a consortium. Library staff will be able to creating holdings and items under a Shadow Instance but are not able to modify the Shadow Instance.
Blocking creating Instances by API with other source values except MARC, FOLIO, CONSORTIUM-MARC, and CONSORTIUM-FOLIO.
[MODINV-817](https://issues.folio.org/browse/MODINV-817)

MODINV-817: Shadow Instances - add support for Consortium source values

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
src/main/java/org/folio/inventory/support/ItemUtil.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandlerTest.java

- Adjust multiple Items updates to send DI_ERROR only when no Items Updated, otherwise complete with partial success
- if the incoming Item is in stored item representation map it to mapping representation to handle multiple actions on single matched item

[MODINV-855] Adjust multiple Items updates to send DI_ERROR only when only when no Items Updated

---

src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/AbstractLoader.java

[MODINV-862](https://issues.folio.org/browse/MODINV-862) problem 1.
**Description:** catch and handle all exceptions since in the reproduced case `DecodeException` was not handled and a job stuck.

MODINV-862: Catch any exception

---

descriptors/ModuleDescriptor-template.json

Add necessary interface into required interfaces in mod-inventory md
[MODINV-863](https://issues.folio.org/browse/MODINV-863)

MODINV-863:  Add necessary interface into required interfaces in mod-inventory md

---

NEWS.md
src/main/java/org/folio/inventory/consortium/consumers/ConsortiumInstanceSharingHandler.java
src/main/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandler.java
src/main/java/org/folio/inventory/dataimport/consumers/QuickMarcKafkaHandler.java

Upgrade folio-kafka-wrapper to 3.0.0 version
Upgrade the version of folio-kafka-wrapper to 3.0.0. Check out the readme at https://github.com/folio-org/folio-kafka-wrapper/blob/master/README.md for usage.
Acceptance Criteria
- kafka records are built using KafkaProducerRecordBuilder
- topic names are generated using KafkaTopicNameHelper

MODINV-834: Upgrade folio-kafka-wrapper to 3.0.0 version

---

NEWS.md
src/main/java/org/folio/inventory/DataImportConsumerVerticle.java
src/main/java/org/folio/inventory/consortium/cache/ConsortiumDataCache.java
src/main/java/org/folio/inventory/consortium/services/ConsortiumServiceImpl.java
src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
src/test/java/org/folio/inventory/consortium/cache/ConsortiumDataCacheTest.java
src/test/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandlerTest.java
src/test/java/org/folio/inventory/dataimport/services/ConsortiumServiceTest.java

[MODINV-872](https://issues.folio.org/browse/MODINV-872)
**Description:**  added cache to get and store consortium data configurations
**Testing:** 
Tested locally the flow of Holdings creation

MODINV-872: add cache to get consortium data configurations

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandlerTest.java

[MODDATAIMP-926](https://issues.folio.org/browse/MODDATAIMP-926)
**Depends on PR:** https://github.com/folio-org/data-import-processing-core/pull/309
**Purpose:** restrict updating shadow MARC authority records for member tenants

MODDATAIMP-926: Restrict updating shadow MARC authority records for member tenants

---

src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandlerTest.java

Remove distinct by permanentLocationId for multiple Holdings during mapping if Holdings already contain at the context
Removed test check related to holdings with the same permanentLocationId like in [MODDICORE-366](https://github.com/folio-org/data-import-processing-core/pull/310).

MODDICORE-366: Remove distinct by permanentLocationId for multiple Holdings during mapping if Holdings already contain at the context

---

src/main/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImpl.java
src/main/java/org/folio/inventory/consortium/util/RestDataImportHelper.java
src/test/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImplTest.java

Lack of permission causes an error on record deletion on local tenant. As a result local marc record that should be deleted/marked as deleted is considered during records matching that in turn causes multiple matching error (and error during single record imports for record updates).
The module gets an error response on record deletion but the module logs say that marc record has been deleted.
* add response status verification from request for record deletion in order to complete result and to write log message accordingly
* add and update test
[MODINV-886](https://issues.folio.org/browse/MODINV-886)
Requires: https://github.com/folio-org/mod-consortia/pull/129

MODINV-886 - Problem with Inventory Single Record Imports for UPDATES in member tenant, for shared instances

---

src/main/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImpl.java
src/main/java/org/folio/inventory/consortium/util/RestDataImportHelper.java
src/main/java/org/folio/inventory/services/EntitiesLinksService.java
src/main/java/org/folio/inventory/services/EntitiesLinksServiceImpl.java
src/test/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImplTest.java
src/test/java/org/folio/inventory/dataimport/services/EntitiesLinksServiceTest.java

In a consortium environment, fields in local MARC bib records may be linked to local MARC authority records. However, Instances with source = MARC may also be promoted to be shared to the rest of the consortium. When the Instance with source = MARC is shared, we need to unlink the controlled fields in the MARC bibliographic record from the local MARC authority records.
- Create entity links for sharing authorities on central tenant during Instance sharing process
- Use new default profile "ECS - Create Instance" with **"remove9Subfields" : false** for instance sharing

[MODINV-890] Create entity links for sharing authorities on central tenant during Instance sharing process

---

src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/ItemLoader.java
src/test/java/org/folio/inventory/eventhandlers/MatchItemEventHandlerUnitTest.java

[MODSOURMAN-1035](https://issues.folio.org/browse/MODSOURMAN-1035)
Data import with MARC bit -> Item update fails due to serialization error: `Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type java.util.LinkedHashMap<java.lang.Object,java.lang.Object> from Array value (token JsonToken.START_ARRAY)`
Fix this by expecting JsonArray for ITEM entity

MODINV-911 fix item entity serialization error

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandlerTest.java

When you want to create an item connected to an existing holdings, you match to that holdings hrid and have an action to create item. If you try to create it Item will be errored with NullException in JSON log
Not try to remove holding identifiers from context if them does not exist there

[MODINV-907] Avoid NPE during create of item after match by holding identifier

---

src/main/java/org/folio/inventory/consortium/handlers/FolioInstanceSharingHandlerImpl.java
src/main/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImpl.java
src/test/java/org/folio/inventory/consortium/consumers/ConsortiumInstanceSharingHandlerTest.java
src/test/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImplTest.java

Fix data lost during sharing instances from member tenant to the central
Rewrap JSON object from **instance.getJsonForStorage()** method to contain all elements in JSON arrays as JSON objects

[MODINV-913] Fix data lost during sharing instance from member tenant to the central

---

src/main/java/org/folio/inventory/dataimport/entities/OlHoldingsAccumulativeResults.java
src/main/java/org/folio/inventory/dataimport/entities/OlItemAccumulativeResults.java
src/main/java/org/folio/inventory/dataimport/entities/PartialError.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
src/main/java/org/folio/inventory/domain/items/Item.java
src/main/java/org/folio/inventory/domain/items/Status.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandlerTest.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandlerTest.java

1.Adjust the OL process to handle multiple expired holdings/items.
2. Compose the main handle and retry the result to set partial errors and created holdings/items into context.
3. Fix an issue for the Holdings/Items where the 3rd action for the entity can't processed after OL revealed.
1. Improved the code inside handlers for the updating multiple Holdings+Items.
2. Brand new mechanism for retreiving actual entities via batch, not by one by one.
3. New tests added. Useless tests removed.
JIRA: https://issues.folio.org/browse/MODINV-860
This PR should be merged with the: https://github.com/folio-org/data-import-processing-core/pull/314.

MODINV-860: Adjust Optimistic locking for multiple holdings and multiple items update

---

src/main/java/org/folio/inventory/resources/MoveApi.java

to replace transitive dependency usage collections-generic v4.01 that is going to be removed from di-processing-core library 
due to vulnerability (https://github.com/advisories/GHSA-fjq5-5j5f-mvxh#:~:text=net.sourceforge.collections%3Acollections%2Dgeneric) https://github.com/folio-org/data-import-processing-core/pull/317

MODDICORE-368 - Replace vulnerable transitive collections-generic v4.01 dependency usage

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandlerTest.java

MARC source shared instance overlay fails occasionally on the Poppy consortia bugfest environment.
* provide local tenant id for mapping metadata retrieval for instance update during overlay process flow
* update test
[MODINV-937](https://issues.folio.org/browse/MODINV-937)

MODINV-937 - MARC source shared instance overlay fails occasionally

---

NEWS.md
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingsRecordCollection.java
src/test/java/api/items/ItemApiMoveExamples.java
src/test/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingsRecordCollectionExamples.java

Inventory cannot process Holdings with virtual fields [MODINV-941](https://issues.folio.org/browse/MODINV-941)
customize object mapper
https://javarevisited.blogspot.com/2018/01/how-to-ignore-unknown-properties-parsing-json-java-jackson.html#axzz8NAd4SgHb

MODINV-941 Inventory cannot process Holdings with virtual fields

---

NEWS.md
src/main/java/org/folio/inventory/resources/MoveApi.java
src/test/java/api/holdings/HoldingsApiMoveExamples.java

Added a mechanism to remove extra redundant fields from Holdings Json while using POST holdings/move.
Tests added.
NEWS updated.

MODINV-984: Remove extra fields from 'holdings/move' mechanism

---

NEWS.md
src/main/java/org/folio/inventory/consortium/util/RestDataImportHelper.java

to expose configuration parameters for overriding the interval and the number of attempts for import status check during instance sharing process
[MODINV-950](https://issues.folio.org/browse/MODINV-950)

MODINV-950 - Make configurable params for instance sharing

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODINV-901
Added missed module permission after this PR merged: https://github.com/folio-org/mod-inventory/pull/666/files
This issue causes Karate failures of Thunderjet team with error:
`{
"errors" : [ {
"message" : "io.vertx.core.impl.NoStackTraceThrowable: Error loading consortium data, tenantId: 'testtenant3598671572787159866' response status: '403', body: 'Access for user 'test-user' (00000000-1111-5555-9999-999999999992) requires permission: user-tenants.collection.get'",
"code" : "genericError",
"parameters" : [ ]
} ],
"total_records" : 1
}`

[MODINV-901] Add missed module permissions

---

descriptors/ModuleDescriptor-template.json

It is needed to fix an issue in scope of integration tests problem: 
`status code was: 403, expected: 204, response time in milliseconds: 291, url: https://folio-testing-karate-okapi.ci.folio.org/inventory/instances/f0fe6f14-c37d-4c4c-b7cf-ac56d01b535f/mark-deleted, response: 
Access for user 'test-user' (00000000-1111-5555-9999-999999999992) requires permission: inventory-storage.instances.item.get
classpath:folijet/mod-inventory/features/inventoryFeatureTest.feature:258`

FAT-9975: Additional permissions for soft delete added.

---

src/main/java/org/folio/inventory/dataimport/handlers/matching/preloaders/AbstractPreloader.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/preloaders/HoldingsPreloader.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/preloaders/InstancePreloader.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/preloaders/ItemPreloader.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/preloaders/OrdersPreloaderHelper.java
src/test/java/org/folio/inventory/eventhandlers/preloaders/HoldingsPreloaderTest.java
src/test/java/org/folio/inventory/eventhandlers/preloaders/InstancePreloaderTest.java
src/test/java/org/folio/inventory/eventhandlers/preloaders/ItemPreloaderTest.java
src/test/java/org/folio/inventory/eventhandlers/preloaders/OrdersPreloaderHelperTest.java

Not throw an exception when not matched by POL/VRN
When not found POL, return null loadQuery and not make request on inventory-storage

[MODINV-953] Adjust non-match by POL/VRN logic to not throw an exception

---

NEWS.md
README.MD
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/inventory/resources/TenantApi.java
src/main/java/org/folio/inventory/services/InventoryKafkaTopic.java
src/main/java/org/folio/inventory/services/InventoryKafkaTopicService.java
src/test/java/org/folio/inventory/service/KafkaAdminClientServiceTest.java

Create Kafka topics instead of relying on auto create in mod-inventory [MODINV-957](https://issues.folio.org/browse/MODINV-957)
* create topics
* cover with tests
* update readme and news

MODINV-957 Create Kafka topics instead of relying on auto create in mod-inventory

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java

During update instance there was a missing matched id when instance has source 'folio' type.
Added necessary logic to fill matched id when source type is folio, and add corresponding logic like in creation of instance process.
[MODINV-968](https://folio-org.atlassian.net/browse/MODINV-968)

MODINV-968: FOLIO source filling necessary fields

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/AbstractInstanceEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java

During code review, there was spotted regression added by previous PR after which existing record search is performed always at local tenant during instance update processing
Correct tenantId for retrieving record while instance updating

[MODINV-972] Correct tenantId for retrieving record while instance updating

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java

Two records are displayed in the table and SRS MARC column shows No action.
Added generation to incoming record and fixed status in srm module.
[MODINV-969](https://folio-org.atlassian.net/browse/MODINV-969)

MODINV-969: The duplicate record is created after updating action

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
src/main/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtil.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
src/test/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtilTest.java

Fix a validation error when trying to import a .mrc-file with a record that has 999ff fields with this Job Profile: 
1) Modify Action Profile to remove 999 field
2) Create Instance Action Profile .
Add 999fi validation to CreateinstanceEventHandler
[MODDATAIMP-1001](https://folio-org.atlassian.net/browse/MODDATAIMP-1001)

MODDATAIMP Data import profile - incoming record contains 999

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/services/OrderHelperServiceImpl.java

SPIKE: Remove duplicated action DI_INVENTORY_INSTANCE_CREATED from Kafka event [MODINV-782](https://folio-org.atlassian.net/browse/MODINV-782)
add if condition in OrderHelperServiceImpl

MODINV-782 SPIKE: Remove duplicated action DI_INVENTORY_INSTANCE_CREATED from Kafka event

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandlerTest.java

Job stucks if user matches item and then updates holding
Allow to retrieve ITEM universally during HOLDINGS update

[MODINV-987] Allow to retrieve ITEM universally during HOLDINGS update

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
src/main/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtil.java
src/test/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtilTest.java
src/test/resources/marc/parsedRecord.json
src/test/resources/marc/reorderedParsedRecord.json
src/test/resources/marc/reorderingResultRecord.json

Purpose
Keep 00X field's position when Creating/Deriving/Editing MARC records
Approach
Implemented reorderMarcRecordFields method to keep the right order of MARC records
Checklist
Closes: MODSOURMAN-1137

MODINV-997: keep 00X field's position when Creating/Deriving MARC records

---

NEWS.md
src/main/java/org/folio/inventory/resources/ItemsByHoldingsRecordId.java

The sorting for Items on Instance details page is not worked [MODINV-1001](https://folio-org.atlassian.net/browse/MODINV-1001)
remove sort by barcode logic

MODINV-1001 The sorting for Items on Instance details page is not worked

---

NEWS.md
src/main/java/org/folio/inventory/resources/ItemRepresentation.java
src/main/java/org/folio/inventory/support/JsonHelper.java
src/test/java/org/folio/inventory/resources/ItemRepresentationTest.java
src/test/java/org/folio/inventory/support/JsonHelperTest.java

Do not send nulls when the values are empty in electronicAccess field
Find null values inside electronicAccess object, and remove them
[MODINV-1006](https://folio-org.atlassian.net/browse/MODINV-1006)

MODINV-1006 Avoid null values in the ElectronicAccess object

---

src/main/java/org/folio/inventory/MarcBibUpdateConsumerVerticle.java

Events for MARC Bib update are not handled by MARC Bib Update Handler (_MarcBibUpdateConsumerVerticle_)
Do not use default namespace for the consumer subscription
Closes: [MODINV-1055](https://folio-org.atlassian.net/browse/MODINV-1055)
Related: [MODINV-986](https://folio-org.atlassian.net/browse/MODINV-986)

MODINV-1055: Fix Consumer Subscription for MARC Bib Update events

---

NEWS.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/inventory/resources/UpdateOwnershipApi.java
src/main/java/org/folio/inventory/support/MoveApiUtil.java
src/test/java/api/BoundWithTests.java
src/test/java/api/holdings/HoldingsUpdateOwnershipApiTest.java
src/test/java/api/support/ApiTests.java

Disallow updating holdings ownership with related boundwith
Check for boundWiths relations with incoming holdingsRecordIds, send error message for such holdings
Jira: https://folio-org.atlassian.net/browse/MODINV-1051

[MODINV-1051] Disallow updating holdings ownership with related boundwith

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtil.java
src/test/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtilTest.java

[MODINV-1049](https://folio-org.atlassian.net/browse/MODINV-1049) Existing "035" field is not retained the original position in imported record
* fix replace old oclc 035 field with normalized data
* add test

MODINV-1049 Existing "035" field is not retained the original position in imported record

---

ramls/holdings_update_ownership.json
src/main/java/org/folio/inventory/resources/UpdateOwnershipApi.java
src/test/java/api/holdings/HoldingsUpdateOwnershipApiTest.java
src/test/java/api/support/builders/HoldingsRecordUpdateOwnershipRequestBuilder.java

Allow update ownership of holdings records with new id
Add new 'targetTenantLocationId' field to request body and set this field to holdings during create at target tenant
https://folio-org.atlassian.net/browse/MODINV-1060

[MODINV-1060] Update ownership of holdings with new location

---

descriptors/ModuleDescriptor-template.json
pom.xml
ramls/inventory.raml
ramls/tenantItemPair.json
ramls/tenantItemPairCollection.json
src/main/java/org/folio/inventory/InventoryVerticle.java
src/main/java/org/folio/inventory/resources/Items.java
src/main/java/org/folio/inventory/resources/TenantItems.java
src/test/java/api/ApiTestSuite.java
src/test/java/api/items/TenantItemApiTests.java
src/test/java/api/support/ApiRoot.java
src/test/java/support/fakes/FakeOkapi.java

[[MODINVSTOR-1243] Implement endpoint to retrieve items from multiple tenants
](https://folio-org.atlassian.net/browse/MODINVSTOR-1243)
- Add new types for receiving request body
- Add new endpoint
- Add endpoint handle to fetch items from different tenants
Verified and left comment on JIRA ticket: https://folio-org.atlassian.net/browse/MODINVSTOR-1243?focusedCommentId=226464

[MODINVSTOR-1243] Implement endpoint to retrieve items from multiple tenants

---

pom.xml
ramls/tenantItemResponse.json
src/main/java/org/folio/inventory/resources/TenantItems.java
src/test/java/api/items/TenantItemApiTests.java

[[MODINV-1070] Modify TenantItems response schema](https://folio-org.atlassian.net/browse/MODINV-1070)
- Modify TenantItems response schema

[MODINV-1070] Modify TenantItems response schema

---

NEWS.md
descriptors/ModuleDescriptor-template.json
ramls/instance.json
src/main/java/org/folio/inventory/config/InventoryConfigurationImpl.java
src/main/java/org/folio/inventory/domain/instances/Dates.java
src/main/java/org/folio/inventory/domain/instances/Instance.java
src/test/java/api/InstancesApiExamples.java
src/test/java/org/folio/inventory/domain/instances/DatesTest.java

[MODINV-1067](https://folio-org.atlassian.net/browse/MODINV-1067) Currently in the Instance schema, there is a field for publication date. However, this data originates from an uncontrolled string in variable fields of the MARC record. The dates in the 008 are more consistently formatted, and are more useful for certain materials like serials. Previously, we implemented sortable properties (publicationPeriod.start/publicationPeriod.end) that are parsed from the publication date field. We need to break this relationship, and instead make the source of that data the elements from the 008. The 008 structure allows for a single position to indicate the type of date that will be represented in the following positions. 
1. Add three new properties to the Instance schema:
- dateTypeId
- date1
- …

feat(instance-date-type-fields): add new date type fields to Instance schema

---

descriptors/ModuleDescriptor-template.json

Allow update ownership without adding user-tenants.collection.get permission to user
Add user-tenants.collection.get to update-ownership API
https://folio-org.atlassian.net/browse/MODINVSTOR-1253

[MODINVSTOR-1253] Add user-tenants.collection.get to update-ownership API

---

descriptors/ModuleDescriptor-template.json

https://folio-org.atlassian.net/browse/MODORDSTOR-419
- kafka consumer in mod-orders-storage fetch central tenant from user-tenants

[MODORDSTOR-419] - Add user-tenants permission for kafka process

---

NEWS.md
descriptors/ModuleDescriptor-template.json

[MODINV-1079](https://folio-org.atlassian.net/browse/MODINV-1079)
Update interfaces versions
`holdings-storage 8.0`
`bound-with-parts-storage 2.0`
Update the module permissions in ModuleDescriptor-template.json file for those endpoints that use the mod-inventory-storage endpoints listed below with new permissions:
"methods": ["POST"],
"pathPattern": "/instance-storage/instances/retrieve",
"permissionsRequired": ["inventory-storage.instances.retrieve.collection.post"]
"methods": ["POST"],
"pathPattern": "/holdings-storage/holdings/retrieve",
"permissionsRequired": ["inventory-storage.holdings.retrieve.collection.post"]

MODINV-1079 holdings-storage and bound-with-parts-storage update

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java

In Quesnelia when we create a marc instance with marking "suppressDiscovery" as true by Data import, suppressDiscovery is displayed as "true" in the folio inventory UI. but in SRS suppressDiscovery is marked as "false".  
On Poppy, this functionality works as expected.
Additional setting suppressFromDiscovery added.
Tests extended.

MODINV-1094: Update suppressDiscovery in the MARC file when creatingan instance with “suppressDiscovery=true” when importing data.

---

NEWS.md
src/main/java/org/folio/inventory/client/OrdersClient.java
src/main/java/org/folio/inventory/common/Context.java
src/main/java/org/folio/inventory/common/MessagingContext.java
src/main/java/org/folio/inventory/common/WebContext.java
src/main/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/util/EventHandlingUtil.java
src/main/java/org/folio/inventory/domain/CollectionProvider.java
src/main/java/org/folio/inventory/storage/Storage.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageCollections.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleAuthorityRecordCollection.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleCollection.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingsRecordCollection.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingsRecordsSourceCollection.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleInstanceCollection.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleItemCollection.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleUserCollection.java
src/test/java/api/ApiTestSuite.java
src/test/java/org/folio/inventory/storage/external/ExternalInstanceCollectionExamples.java
src/test/java/org/folio/inventory/storage/external/ExternalItemCollectionExamples.java
src/test/java/org/folio/inventory/storage/external/ExternalStorageModuleAuthorityRecordCollectionExamples.java
src/test/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingsRecordCollectionExamples.java
src/test/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingsRecordsSourceCollectionExamples.java
src/test/java/org/folio/inventory/storage/external/failure/ExternalAuthorityCollectionBadRequestExamples.java
src/test/java/org/folio/inventory/storage/external/failure/ExternalAuthorityCollectionServerErrorExamples.java
src/test/java/org/folio/inventory/storage/external/failure/ExternalInstanceCollectionBadRequestExamples.java
src/test/java/org/folio/inventory/storage/external/failure/ExternalInstanceCollectionServerErrorExamples.java
src/test/java/org/folio/inventory/storage/external/failure/ExternalItemCollectionBadRequestExamples.java
src/test/java/org/folio/inventory/storage/external/failure/ExternalItemCollectionServerErrorExamples.java

[MODINV-1134](https://folio-org.atlassian.net/browse/MODINV-1134) Missing x-okapi-user-id header in communications with inventory-storage
* add missing headers
* fix tests

MODINV-1134 Missing x-okapi-user-id header in communications with inventory-storage

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/inventory/dataimport/handlers/actions/AbstractAuthorityEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateHoldingEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateMarcHoldingsEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/DeleteAuthorityEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateMarcHoldingsEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/modify/AbstractModifyEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/AbstractMarcMatchEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/AbstractMatchEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/MarcBibliographicMatchEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/util/EventHandlingUtil.java
src/main/resources/log4j2-json.properties
src/main/resources/log4j2.properties

[MODINV-1115](https://issues.folio.org/browse/MODINV-1115) Adjust permissions for system user
To support DI operation in Eureka, we should implement support for performing asynchronous operations on behalf of a system user.
Approach
Handle data-import events with null or empty token

MODINV-1115 Assign permissions to System User

---

src/main/java/org/folio/inventory/consortium/util/InstanceOperationsHelper.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
src/main/java/org/folio/inventory/dataimport/util/DataImportConstants.java
src/test/java/org/folio/inventory/consortium/util/InstanceOperationsHelperTest.java

after introducing transactional saving of an instance in mod-inventory-storage
error responses where returning in different format, as PgUtil can not be used as transactional wrapper
[MODINV-1151](https://folio-org.atlassian.net/browse/MODINV-1151)
* handle duplicates
* add test

MODINV-1151 Handle deduplication in mod-inventory

---

descriptors/ModuleDescriptor-template.json

[MODINV-1155](https://folio-org.atlassian.net/browse/MODINV-1155) Add missing required interfaces to Module Descriptor

MODINV-1155 Add missing required interfaces to Module Descriptor

---

NEWS.md
pom.xml
src/main/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/InstanceUpdateDelegate.java
src/main/java/org/folio/inventory/domain/SynchronousCollection.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleInstanceCollection.java
src/test/java/org/folio/inventory/dataimport/handlers/MarcBibUpdateKafkaHandlerTest.java

Fix handling optimistic locking error on updating inventory instance record while handling Marc Bib Update event and implement proper retry mechanism
Do not wrap OptimisticLocking error inside the other one so that it is possible to handle it in the Marc Bib update event handler
[MODSOURCE-832](https://folio-org.atlassian.net/browse/MODSOURCE-832)
[MODINV-1125](https://folio-org.atlassian.net/browse/MODINV-1125)
[MODELINKS-286](https://folio-org.atlassian.net/browse/MODELINKS-286)

Release v21.0.9: MODINV-1125 - Fix handling optimistic locking behavior for instance update when consuming Marc Bib update event

---

NEWS.md
pom.xml
src/main/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/InstanceUpdateDelegate.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/util/EventHandlingUtil.java
src/main/java/org/folio/inventory/domain/SynchronousCollection.java
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleInstanceCollection.java
src/test/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandlerTest.java

Fix handling optimistic locking error on updating inventory instance record while handling Marc Bib Update event and implement proper retry mechanism
Do not wrap OptimisticLocking error inside the other one so that it is possible to handle it in the Marc Bib update event handler
[MODSOURCE-817](https://folio-org.atlassian.net/browse/MODSOURCE-817)
[MODINV-1100](https://folio-org.atlassian.net/browse/MODINV-1100)
[MODELINKS-115](https://folio-org.atlassian.net/browse/MODELINKS-115)

Release v20.2.11: MODINV-1125 - Fix handling optimistic locking behavior for instance update when consuming Marc Bib update event

---

NEWS.md
src/main/java/org/folio/inventory/instanceingress/handler/InstanceIngressEventHandler.java

[MODINV-1161](https://folio-org.atlassian.net/browse/MODINV-1161)
Update the snapshot status from `PROCESSING_FINISHED` to `COMMITTED`, as  the snapshot with the `PROCESSING_FINISHED` status does not work correctly during the process of persisting the record in the SRS module, which results in two records with the `ACTUAL` state for the same `matched_id` in the `records_lb` table.
For example:
<kbd>
</kbd>

fix(snapshot-status): Update the snapshot status from PROCESSING_FINISHED to COMMITTED

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/handlers/matching/AbstractMarcMatchEventHandler.java
src/main/java/org/folio/inventory/dataimport/handlers/matching/MarcBibliographicMatchEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
src/test/java/org/folio/inventory/dataimport/handlers/matching/MarcBibliographicMatchEventHandlerTest.java

provide support for narrowing down marc-bib multiple match result using a sub-match profile
* use instance ids that represent result of multiple matching from previous matching processing to build additional condition for records matching during sub-match profile processing
* add tests
* additionally: update test to verify the deduplication logic of CreateInstanceEventHandler reliably
[MODINV-1114](https://issues.folio.org/browse/MODINV-1114)

MODINV-1114 - Implement marc bib submatch

---

src/main/java/org/folio/inventory/dataimport/handlers/matching/AbstractMarcMatchEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/matching/MarcBibliographicMatchEventHandlerTest.java

to fix check for the case when there are no records matching criteria on a tenant in a non-consortium environment
[FAT-18739](https://issues.folio.org/browse/FAT-18739)

FAT-18739 - Fix check for case if no records matching criteria on non-consortium tenant

---

NEWS.md
src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateAuthorityEventHandler.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateAuthorityEventHandlerTest.java

to prevent sending events if id duplication error occurs during authority creation as a result of handling duplicated events
* update deduplication logic condition according to response returned on authority creation attempt
* update test
[MODSOURMAN-1282](https://issues.folio.org/browse/MODSOURMAN-1282)

MODINV-1168 - Actualize condition of deduplication logic for authority creation

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/InstanceUpdateDelegate.java
src/test/java/org/folio/inventory/eventhandlers/UpdateInstanceQuickMarcEventHandlerTest.java

Update "deleted" markers when leader 05 value is changed
Keep staffSuppressed and discoverySuppressed true if delete leader changed using QuickMarc
https://folio-org.atlassian.net/browse/MODSOURCE-760

[MODSOURCE-760] Keep staffSuppressed and discoverySuppressed true if delete leader changed using QuickMarc

---

src/main/java/org/folio/inventory/resources/Instances.java

correct the response check to avoid false positive error message when, in fact, a record is successfully updated.
> The instance wasn't undeleted in SRS. InstanceID: 3b99cb77-db4f-4f7b-88da-22dbae6d4684, SC: 204

FAT-19198 - Corrected response check on record undelete request

---

src/main/java/org/folio/inventory/dataimport/handlers/actions/InstanceUpdateDelegate.java
src/main/java/org/folio/inventory/domain/instances/Instance.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandlerTest.java
src/test/java/org/folio/inventory/eventhandlers/UpdateInstanceQuickMarcEventHandlerTest.java
src/test/resources/handlers/bib-rules.json
src/test/resources/handlers/deleted-bib-record.json

Fix Suppressing from discovery MARC instances makes records also staff suppressed
Change staff suppressed and discovery suppressed to true only if the leader changed from valid to 'd' otherwise keep existing values

[MODINV-1180] Fix Suppressing from discovery MARC instances makes records also staff suppressed

---

NEWS.md
src/main/java/org/folio/inventory/instanceingress/handler/InstanceIngressEventHandler.java
src/test/java/org/folio/inventory/instanceingress/handler/CreateInstanceIngressEventHandlerUnitTest.java
src/test/java/org/folio/inventory/instanceingress/handler/UpdateInstanceIngressEventHandlerUnitTest.java

Earlier,  a single cache for used for caching `MappingMetadata` across all the tenants. This caused the MARC record processing to fail when the reference data ID in one tenant differed from the reference data ID in another tenant.
With the new approach, the `MappingMetadata` is cached for each tenant separately. As a result, the MARC processing should work even when different tenants have different reference data IDs.
**Another optimization we could do in future:**
[Here](https://github.com/folio-org/mod-inventory/blob/master/src/main/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandler.java#L118) we use `jobId` as the cache Key. May be use tenantId instead? This way, both [InstanceIngressEventHandler.java](https://github.com/folio-org/mod-inventory/pull/834/files#diff-7 …

MODINV-1205: Use tenant specific cache for MappingMetadata

---

src/main/java/org/folio/inventory/resources/UpdateOwnershipApi.java
src/test/java/api/holdings/HoldingsUpdateOwnershipApiTest.java
src/test/java/api/items/ItemUpdateOwnershipApiTest.java
src/test/java/api/support/builders/ItemRequestBuilder.java

Unable to update ownership of item with filled temporary/permanent location
Set item locations null during updateOwnership
https://folio-org.atlassian.net/browse/MODINV-1175

[MODINV-1175] Set item locations null during updateOwnership

---

src/main/java/org/folio/inventory/dataimport/util/ParsedRecordUtil.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java
src/test/java/org/folio/inventory/dataimport/util/ParsedRecordUtilTest.java

to fix issue when MARC record becomes corrupted after update of instance that was previously set for deletion
* put parsed content as String instead of JsonObject to properly serialize it for request body, as it is done by other util methods that change marc content fields
* add tests
[MODSOURCE-898](https://issues.folio.org/browse/MODSOURCE-898)
[MODINV-1232](https://issues.folio.org/browse/MODINV-1232)

MODINV-1232 - Deleted from Inventory MARC records are not matching during update

---

NEWS.md
pom.xml
src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleInstanceCollection.java
src/test/java/org/folio/inventory/storage/external/ExternalInstanceCollectionExamples.java
src/test/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingsRecordsSourceCollectionExamples.java
src/test/java/org/folio/inventory/storage/external/ExternalStorageTests.java

retain original source value of the source "LINKED_DATA" instance when the instance is updated after linked authority update
* leave source value of the existing instance during instance update
* add test
[MODINV-1176](https://issues.folio.org/browse/MODINV-1176)
Tests execution has been ensured on Jenkins for external storage collections

MODINV-1176 - Source of Instance changes from LINKED_DATA to MARC when a linked authority is updated

---

NEWS.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/inventory/client/InstanceLinkClient.java
src/main/java/org/folio/inventory/consortium/util/MarcRecordUtil.java
src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
src/main/java/org/folio/inventory/dataimport/exceptions/InstanceLinksException.java
src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
src/main/java/org/folio/inventory/instanceingress/handler/UpdateInstanceIngressEventHandler.java
src/test/java/org/folio/inventory/client/InstanceLinkClientTest.java
src/test/java/org/folio/inventory/consortium/util/MarcRecordUtilTest.java
src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java

Add instance-authority links logic on MARC Instance update
[MODINV-1068](https://folio-org.atlassian.net/browse/MODINV-1068)
- Implement links client
- Use MarcBibRecordModifier on Instance replacement when Instance source is MARC
Tested on dev Rancher with telepresence, works as expected, $9 is not removed from record, record editable via quick-marc

feat(instance-authority-links): Add instance-authority links logic on MARC Instance update

---

pom.xml
src/main/java/org/folio/inventory/support/KafkaConsumerVerticle.java

to configure "group.instance.id" property during consumer wrapper creation
[MODINV-1272](https://issues.folio.org/browse/MODINV-1272)

MODINV-1272 - Set groupInstanceId property during consumer wrapper creation

---

NEWS.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/inventory/resources/AbstractInstances.java
src/main/java/org/folio/inventory/resources/Instances.java
src/main/java/org/folio/inventory/support/http/server/RedirectResponse.java
src/test/java/api/InstancesApiExamples.java
src/test/java/api/PrecedingSucceedingTitlesApiExamples.java

to include newly created instance in a response on the `POST /inventory/instances` endpoint
* send created instance in a response
* update tests
[MODINV-1078](https://issues.folio.org/browse/MODINV-1078)
The "inventory" interface version increment made in the #855 has been reverted because for Trillium, the version had already been bumped in the previous PR #845.

MODINV-1078 - POST to /inventory/instances does not return newly-created object

---

NEWS.md
src/main/java/org/folio/inventory/consortium/cache/ConsortiumDataCache.java
src/main/java/org/folio/inventory/consortium/services/ConsortiumServiceImpl.java
src/main/java/org/folio/inventory/resources/MoveApi.java

Improved logging for the “move” holdings operation.

MODINV-1276: Can't move holdings/items to another instance
