- Jenkinsfile
> Update Jenkinsfile to publish mod descriptor

- descriptors/ModuleDescriptor-template.json
> Update permissions in module descriptor

- Dockerfile
- build.gradle
- descriptors/DeploymentDescriptor-template.json
- register-managed.sh
- register.sh
- start.sh
- test-storage.sh
- test-via-okapi.sh
- unregister-managed.sh
- unregister.sh
> FOLIO-813 artifact mod- prefix

- Jenkinsfile
- Jenkinsfile.gradle
- NEWS.md
- descriptors/DeploymentDescriptor-template.json
- descriptors/ModuleDescriptor-template.json
- ramls/examples/items_get.json
- ramls/ingest_status.json
- src/test/groovy/org/folio/inventory/storage/ItemCollectionExamples.groovy
- src/test/java/support/fakes/FakeOkapi.java
> FOLIO-351 whitespace tidy 1

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/inventory.raml
- ramls/item.json
- src/main/java/org/folio/inventory/resources/ItemRepresentation.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleItemCollection.java
- src/test/java/api/ItemApiExamples.java
Provides inventory interface 4.1
Requires item-storage interface 4.1
> Make title optional for an item MODINV-34

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- okapi-registration/unmanaged-deployment/register.sh
- pom.xml
- ramls/inventory.raml
- src/main/java/org/folio/inventory/domain/ingest/IngestMessageProcessor.java
- src/main/java/org/folio/inventory/resources/ingest/ModsIngestion.java
- src/test/java/api/ApiTestSuite.java
- src/test/java/api/InstancesApiExamples.java
- src/test/java/api/ModsIngestExamples.java
- src/test/java/api/support/ControlledVocabularyPreparation.java
- src/test/java/api/support/InstanceSamples.java
- src/test/java/api/support/builders/InstanceRequestBuilder.java
- src/test/java/support/fakes/FakeOkapi.java
- test-via-okapi.sh
> Merge changes for inventory reference data

- ramls/ingest_status.json
- ramls/instance.json
- ramls/instance_context.json
- ramls/instances.json
- ramls/item.json
- ramls/items.json
This copies the instance.json descriptions from mod-inventory-storage, and adds some others.
> MODINV-87 schema descriptions 1

- pom.xml
From report plugin to main plugin
> Move surefire workaround config from FOLIO-1609

- descriptors/ModuleDescriptor-template.json
- ramls/inventory.raml
- ramls/item.json
- src/main/java/org/folio/inventory/domain/ingest/IngestMessageProcessor.java
- src/main/java/org/folio/inventory/domain/items/Item.java
- src/main/java/org/folio/inventory/domain/items/Status.java
- src/main/java/org/folio/inventory/resources/ItemRepresentation.java
- src/main/java/org/folio/inventory/resources/Items.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleItemCollection.java
- src/test/java/api/support/builders/ItemRequestBuilder.java
- src/test/java/org/folio/inventory/storage/external/ExternalItemCollectionExamples.java
- src/test/java/org/folio/inventory/storage/external/failure/ExternalItemCollectionFailureExamples.java
Requires `item-storage` interface version 7.3
> Propagate new Item property status.date MODINV-104

- src/main/java/org/folio/inventory/InventoryVerticle.java
- src/main/java/org/folio/inventory/resources/Instances.java
- src/main/java/org/folio/inventory/resources/Items.java
- src/main/java/org/folio/inventory/resources/ingest/ModsIngestion.java
- src/main/java/org/folio/inventory/storage/Storage.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageCollections.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleCollection.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingCollection.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleInstanceCollection.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleItemCollection.java
- src/test/java/org/folio/inventory/storage/external/ExternalInstanceCollectionExamples.java
- src/test/java/org/folio/inventory/storage/external/ExternalItemCollectionExamples.java
- src/test/java/org/folio/inventory/storage/external/failure/ExternalInstanceCollectionBadRequestExamples.java
- src/test/java/org/folio/inventory/storage/external/failure/ExternalInstanceCollectionServerErrorExamples.java
- src/test/java/org/folio/inventory/storage/external/failure/ExternalItemCollectionBadRequestExamples.java
- src/test/java/org/folio/inventory/storage/external/failure/ExternalItemCollectionServerErrorExamples.java
Reduce HttpClient creation to 1 time in the launch verticle and reuse the single HttpClient throughout the module.
> Fix for MODINV-102

- README.MD
Link to dockerhub, sonarqube, apidocs
> FOLIO-473 add links to README additional info

- descriptors/ModuleDescriptor-template.json
- ramls/isbn.raml
- src/main/java/org/folio/inventory/resources/IsbnUtilsApi.java
- src/main/java/org/folio/inventory/support/http/server/JsonResponse.java
- src/test/java/api/isbns/IsbnUtilsApiExamples.java
https://issues.folio.org/browse/MODINV-139
- raml: Modified 400 Error code to return text/plain response instead of application/json
- Modified Unit tests accordingly
> MODINV-139- 400/422 error reporting

- descriptors/ModuleDescriptor-template.json
- ramls/examples/item_get.json
- ramls/examples/items_get.json
- ramls/inventory.raml
- ramls/item.json
- src/main/java/org/folio/inventory/domain/items/Item.java
- src/main/java/org/folio/inventory/resources/ItemRepresentation.java
- src/main/java/org/folio/inventory/resources/Items.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleItemCollection.java
- src/test/java/api/items/ItemApiExamples.java
- src/test/java/api/support/builders/ItemRequestBuilder.java
Due to https://issues.folio.org/browse/MODINV-147 we would like to introduce tags for item entities.
* updated item with tags
* updated interfaces versions
* updated items implementation to include tags
* updated item tests accordingly
> MODINV-147 Inventory App: Assign tags to item record

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/inventory/InventoryVerticle.java
- src/main/java/org/folio/inventory/domain/AsynchronousCollection.java
- src/main/java/org/folio/inventory/domain/BatchResult.java
- src/main/java/org/folio/inventory/resources/AbstractInstances.java
- src/main/java/org/folio/inventory/resources/Instances.java
- src/main/java/org/folio/inventory/resources/InstancesBatch.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleCollection.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleInstanceCollection.java
- src/test/java/api/InstancesApiExamples.java
- src/test/java/support/fakes/FakeOkapi.java
- src/test/java/support/fakes/FakeStorageModule.java
https://issues.folio.org/browse/MODINV-134
- changed logic of post /inventory/instances/batch using new batch save endpoint in inventory-storage to create Instances
- updated tests
> MODINV-134 - Update batch post instances to send batch save to inventory-storage

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/instance.json
- ramls/inventory-batch.raml
- ramls/inventory.raml
- src/main/java/org/folio/inventory/domain/instances/Instance.java
- src/main/java/org/folio/inventory/resources/AbstractInstances.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleInstanceCollection.java
- src/test/java/api/ApiTestSuite.java
- src/test/java/api/InstancesApiExamples.java
- src/test/java/api/support/http/ResourceClient.java
- src/test/java/api/support/http/StorageInterfaceUrls.java
- src/test/java/support/fakes/FakeOkapi.java
-added the natureOfContentTermIds field to the Instance
> MODINV-149 UIIN-470: Backend for nature of content on Instance

- src/test/java/api/ApiTestSuite.java
- src/test/java/support/fakes/FakeOkapi.java
Changed some tests regarding changes in MODINVSTOR-315:
"code" property was added for location-unit.
> MODINV-158: Fix the impact of the API change as per MODINVSTOR-315 for mod-inventory

- descriptors/ModuleDescriptor-template.json
- ramls/inventory.raml
- ramls/item.json
- src/main/java/org/folio/inventory/domain/ingest/IngestMessageProcessor.java
- src/main/java/org/folio/inventory/domain/items/Item.java
- src/main/java/org/folio/inventory/domain/items/LastCheckIn.java
- src/main/java/org/folio/inventory/resources/ItemRepresentation.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleItemCollection.java
- src/test/java/api/items/ItemApiExamples.java
Show most recent check in on item record.
Resolves: MODINV-173
See MODINVSTOR-386 and CIRC-522 for reference.
> MODINV-173: Add last check in properties to item representation

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/inventory.raml
- ramls/item.json
- src/main/java/org/folio/inventory/domain/items/Item.java
- src/main/java/org/folio/inventory/domain/items/ItemStatusName.java
- src/main/java/org/folio/inventory/domain/items/Status.java
- src/main/java/org/folio/inventory/resources/ItemRepresentation.java
- src/main/java/org/folio/inventory/resources/Items.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleItemCollection.java
- src/main/java/org/folio/inventory/support/JsonHelper.java
- src/main/java/org/folio/inventory/support/http/server/JsonResponse.java
- src/main/java/org/folio/inventory/validation/ItemStatusValidator.java
- src/test/java/api/items/ItemApiExamples.java
- src/test/java/api/support/builders/ItemRequestBuilder.java
- src/test/java/org/folio/inventory/storage/external/ExternalItemCollectionExamples.java
- src/test/java/org/folio/inventory/storage/external/failure/ExternalItemCollectionFailureExamples.java
- src/test/java/support/fakes/FakeOkapi.java
- src/test/java/support/fakes/FakeStorageModule.java
- src/test/java/support/fakes/processors/StorageRecordPreProcessors.java
https://issues.folio.org/browse/MODINV-189: Item-storage 8.0 breaking changes
This story includes changes required by breaking stories:
* MODINVSTOR-283 Restrict item states
* MODINVSTOR-332 Item: Change array copyNumbers to simple property copyNumber (breaking)
* MODINVSTOR-392 Make item.status.date read only field.
**Must be merged after:** https://github.com/folio-org/mod-inventory-storage/pull/382
> [BREAKING] MODINV-189: item-storage 8.0 updates

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
- src/main/java/org/folio/inventory/dataimport/util/ParsedRecordUtil.java
- src/main/java/org/folio/inventory/resources/EventHandlers.java
- src/main/java/org/folio/inventory/resources/Items.java
- src/main/java/org/folio/inventory/support/ItemUtil.java
- src/main/resources/MessagingDescriptor.json
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandlerTest.java
https://issues.folio.org/browse/MODINV-184
* implemented action handler for Create Item action.
*  published event about Item creation using data-import-processing-core
> MODINV-184 - Implement action handler for Create Item action

- pom.xml
- ramls/holdings-record.json
- src/main/java/org/folio/inventory/dataimport/HoldingWriterFactory.java
- src/main/java/org/folio/inventory/dataimport/ItemWriterFactory.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateHoldingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/AbstractMatchEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/MatchHoldingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/MatchItemEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/HoldingLoader.java
- src/main/java/org/folio/inventory/domain/HoldingsRecordCollection.java
- src/main/java/org/folio/inventory/resources/EventHandlers.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingsRecordCollection.java
- src/main/resources/MessagingDescriptor.json
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateHoldingEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandlerTest.java
- src/test/java/org/folio/inventory/eventhandlers/MatchHoldingEventHandlerUnitTest.java
- src/test/java/org/folio/inventory/eventhandlers/MatchInstanceEventHandlerUnitTest.java
- src/test/java/org/folio/inventory/eventhandlers/MatchItemEventHandlerUnitTest.java
- src/test/java/org/folio/inventory/storage/external/ExternalStorageModuleHoldingsRecordCollectionTest.java
Upgrade MODINV's library, based on MODDICORE recent work
> MODINV-219 Upgrade MODINV's library, based on MODDICORE recent work

- src/main/java/org/folio/inventory/resources/AbstractInstances.java
- src/main/java/org/folio/inventory/resources/Instances.java
- src/test/java/api/ApiTestSuite.java
- src/test/java/api/InstanceRelationshipsTest.java
https://issues.folio.org/browse/MODINV-272
> MODINV-272: [RELEASE] Inventory. Instance. Instance relationship data is not saved

- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/AbstractLoader.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/HoldingLoader.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/InstanceLoader.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/ItemLoader.java
- src/main/java/org/folio/inventory/resources/EventHandlers.java
- src/test/java/org/folio/inventory/eventhandlers/MatchHoldingEventHandlerUnitTest.java
- src/test/java/org/folio/inventory/eventhandlers/MatchInstanceEventHandlerUnitTest.java
- src/test/java/org/folio/inventory/eventhandlers/MatchItemEventHandlerUnitTest.java
https://issues.folio.org/browse/MODINV-275 - Matcher did not find an existing instance by title
added workerExecutor for value loaders
> MODINV-275 - Matcher did not find an existing instance by title

- pom.xml
Update data-import-processing-core dependency to v1.1.2 and mod-pubsub-client to v1.1.4
> MODINV-281 pubsub and data-import-processing-core dependencies

- NEWS.md
- pom.xml
- Updated data-import-processing-core dependency to v1.1.2
- Updated mod-pubsub-client dependency to v1.1.4
- Updated mod-source-record-storage-client to v3.1.4
> MODINV-282 Release v14.1.3 with updated dependencies

- pom.xml
JIRA-ticket: https://issues.folio.org/browse/MODINV-285
> MODINV-285 - Updated dependency to data-import-processing-core

- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/AbstractLoader.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/HoldingLoader.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/InstanceLoader.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/ItemLoader.java
- src/main/java/org/folio/inventory/resources/EventHandlers.java
- src/test/java/org/folio/inventory/eventhandlers/MatchHoldingEventHandlerUnitTest.java
- src/test/java/org/folio/inventory/eventhandlers/MatchInstanceEventHandlerUnitTest.java
- src/test/java/org/folio/inventory/eventhandlers/MatchItemEventHandlerUnitTest.java
JIRA-ticket: https://issues.folio.org/browse/MODINV-283
> MODINV-283 - Inventory search hangs

- pom.xml
- src/main/java/org/folio/inventory/resources/EventHandlers.java
- src/test/java/api/events/EventHandlersApiTest.java
1. Unzipping added.
2. 'org.apache.commons' changed on 'commons-io' with the actual version.
3. Tests changed.
> MODINV-284: Archive event payload (#193)

- ramls/instance.json
- src/main/java/org/folio/inventory/domain/instances/titles/PrecedingSucceedingTitle.java
- src/main/java/org/folio/inventory/resources/AbstractInstances.java
- src/test/java/api/PrecedingSucceedingTitlesApiExamples.java
JIRA-ticket: https://issues.folio.org/browse/MODINV-294
> MODINV-294 - Instance precedingTitles and succedingTitles can not be mapped from response

- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
- src/main/java/org/folio/inventory/resources/EventHandlers.java
- src/main/java/org/folio/inventory/support/ItemUtil.java
- src/main/resources/MessagingDescriptor.json
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandlerTest.java
ticket: https://issues.folio.org/browse/MODINV-259
* implemented action handler for Update Item action.
*  published event about Item updating using data-import-processing-core
> MODINV-259 - Enable Action profile action for incoming MARC Bibs: Replace Inventory Item records

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/inventory/InventoryVerticle.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
- src/main/java/org/folio/inventory/resources/EventHandlers.java
- src/main/java/org/folio/inventory/support/http/client/OkapiHttpClient.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
ticket: https://issues.folio.org/browse/MODINV-302
* expanded CreateInstanceEventHandler with logic to save preceding/succeeding titles from a newly mapped instance
> MODINV-302 - Expand handler for instance creation with logic to post preceding/succeeding titles

- descriptors/ModuleDescriptor-template.json
- pom.xml
Update SRS client dependency to v3.2.0
Update pubsub dependency to 1.2.0
Update data-import-processing-core dependency to 2.1.1
Add dependency on "source-storage-suppress-discovery" interface
> MODINV-313 Update client dependencies

- pom.xml
MODINV-218 introduced a implementation compatibility breaking change, the next version should be 15.0.0 rather than 14.2.0
> Change next version to 15.0.0 MODINV-301 MODINV-218

- pom.xml
Update data-import-processing-core lib to snapshot version for testing new functionality on hosted envs
> MODINV-315 Update data-import-processing-core lib version

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/inventory/resources/Instances.java
[MODINV-316](https://issues.folio.org/browse/MODINV-316)
This PR will be merged after SRS refactoring-master branch is merged to master. 
Dependency to SRS v4.0.0 will be updated after all the changes are verified on the envs and SRS module is released.
> MODINV-316 Update SRS client requests for v4

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/inventory.raml
- src/main/java/org/folio/inventory/resources/Items.java
- src/main/java/org/folio/inventory/services/MoveItemIntoStatusService.java
- src/main/java/org/folio/inventory/validation/ItemMarkAsMissingValidators.java
- src/main/java/org/folio/inventory/validation/ItemsValidator.java
- src/main/java/org/folio/inventory/validation/MarkAsMissingValidators.java
- src/main/java/org/folio/inventory/validation/MarkAsWithdrawnValidators.java
- src/test/java/api/ApiTestSuite.java
- src/test/java/api/items/ItemMarkMissingApiTest.java
- src/test/java/api/items/MarkItemMissingApiTests.java
- src/test/java/api/items/MarkItemWithdrawnApiTests.java
- src/test/java/api/support/ApiTests.java
- src/test/java/api/support/dto/Request.java
- src/test/java/api/support/fixtures/ItemMarkMissingFixture.java
- src/test/java/api/support/fixtures/ItemMarkWithdrawnFixture.java
- src/test/java/api/support/fixtures/MarkItemMissingFixture.java
- src/test/java/api/support/fixtures/MarkItemWithdrawnFixture.java
- src/test/java/api/support/http/BusinessLogicInterfaceUrls.java
- src/test/java/api/support/http/ResourceClient.java
- src/test/java/support/matchers/ItemMatchers.java
- src/test/java/support/matchers/JsonObjectMatchers.java
- src/test/java/support/matchers/RequestMatchers.java
https://issues.folio.org/browse/MODINV-312 - BE: Awaiting delivery --> Missing does not change request status
Implement process-oriented API to mark an item as missing.
> MODINV-312: Implement mark-item-missing API.

- pom.xml
data-import-processing-core v2.1.5 contains fix https://issues.folio.org/browse/MODDICORE-61
> Update dependency on data-import-processing-core v2.1.5

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/util/EventHandlingUtil.java
- src/main/java/org/folio/inventory/resources/EventHandlers.java
- src/main/resources/MessagingDescriptor.json
- src/test/java/org/folio/inventory/eventhandlers/UpdateInstanceEventHandlerUnitTest.java
Add source-record states storing mechanism for QM edit workflow
> MODINV-324 Add source-record states storing mechanism for QM edit

- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateInstanceEventHandler.java
> MODINV-324 Add source-record states storing mechanism for QM edit workflow

- src/main/java/org/folio/inventory/dataimport/handlers/matching/AbstractMatchEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/AbstractLoader.java
- src/main/java/org/folio/inventory/resources/EventHandlers.java
Requires https://github.com/folio-org/data-import-processing-core/pull/82 to be merged first
> MODINV-289 Refactor matching in asynchronous style

- src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandlerTest.java
should be merged after https://github.com/folio-org/data-import-processing-core/pull/88
> MODDICONV-141 - Updated actions for Action profiles

- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/InstanceUpdateDelegate.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateInstanceEventHandler.java
- src/main/java/org/folio/inventory/resources/EventHandlers.java
- src/main/resources/MessagingDescriptor.json
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java
- src/test/java/org/folio/inventory/eventhandlers/UpdateInstanceEventHandlerUnitTest.java
should be merged after folio-org/data-import-processing-core#91
> MODSOURMAN-281 - Added post-processing handler for record modified event

- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandlerTest.java
- src/test/java/org/folio/inventory/eventhandlers/MatchHoldingEventHandlerUnitTest.java
ticket: https://issues.folio.org/browse/MODINV-296
> MODINV-296 - Field mappings: Item - Item status handling logic

- Dockerfile
- Jenkinsfile
- pom.xml
https://issues.folio.org/browse/MODINV-335 - Migrate to java 11.
> MODINV-335: Migrate to java 11.

- NEWS.md
- pom.xml
- ramls/holdings-record.json
- src/main/java/org/folio/inventory/resources/MoveApi.java
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleCollection.java
- src/test/java/api/items/ItemApiMoveExamples.java
[MODINV-363](https://issues.folio.org/browse/MODINV-363) - Release 16.1.2
> MODINV-363 - Release 16.1.2

- src/main/java/org/folio/inventory/validation/status/InProcessNonRequestableTargetItemStatusValidator.java
- src/main/java/org/folio/inventory/validation/status/InProcessTargetItemStatusValidator.java
- src/main/java/org/folio/inventory/validation/status/IntellectualItemTargetItemStatusValidator.java
- src/main/java/org/folio/inventory/validation/status/LongMissingTargetItemStatusValidator.java
- src/main/java/org/folio/inventory/validation/status/MissingTargetItemStatusValidator.java
- src/main/java/org/folio/inventory/validation/status/RestrictedTargetItemStatusValidator.java
- src/main/java/org/folio/inventory/validation/status/UnavailableTargetItemStatusValidator.java
- src/main/java/org/folio/inventory/validation/status/UnknownTargetItemStatusValidator.java
- src/main/java/org/folio/inventory/validation/status/WithdrawnTargetItemStatusValidator.java
- src/test/java/api/items/MarkItemRestrictedApiTests.java
- src/test/java/api/items/MarkItemUnavailableApiTests.java
- src/test/java/org/folio/inventory/validation/status/InProcessItemStatusValidatorTest.java
- src/test/java/org/folio/inventory/validation/status/InProcessNonRequestableItemStatusValidatorTest.java
- src/test/java/org/folio/inventory/validation/status/IntellectualItemStatusValidatorTest.java
- src/test/java/org/folio/inventory/validation/status/LongMissingItemStatusValidatorTest.java
- src/test/java/org/folio/inventory/validation/status/MissingItemStatusValidatorTest.java
- src/test/java/org/folio/inventory/validation/status/RestrictedItemStatusValidatorTest.java
- src/test/java/org/folio/inventory/validation/status/TargetItemStatusValidatorsTest.java
- src/test/java/org/folio/inventory/validation/status/UnavailableStatusValidatorTest.java
- src/test/java/org/folio/inventory/validation/status/UnknownStatusValidatorTest.java
- src/test/java/org/folio/inventory/validation/status/WithdrawnStatusValidatorTest.java
Allowed transitions added according to MODINV-366 request.
> Modinv 366

- descriptors/ModuleDescriptor-template.json
[MODINV-421](https://issues.folio.org/browse/MODINV-421) - update permissions for inventory instanses endpoint
Fix permission errors while executing GET /inventory/instances with 
inventory.instances.collection.get permission for user.
Update module descriptor with needed permissions
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in …
> MODINV-421 - update permissions for inventory instanses endpoint

- descriptors/ModuleDescriptor-template.json
> Revert "MODINV-422 - Update interface version (#348)"

- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateInstanceEventHandler.java
- src/test/java/org/folio/inventory/eventhandlers/UpdateInstanceEventHandlerUnitTest.java
- src/test/java/org/folio/inventory/quickmarc/consumers/QuickMarcKafkaHandlerTest.java
MODINV-439 - Inventory instance record not updating although quickMARC/SRS updates
* changed back value for event payload
> MODINV-439 - Inventory instance record not updating although quickMARC/SRS updates

- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateHoldingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateHoldingEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandlerTest.java
to make the message on the json screen more informative and user-friendly when an action profile has not been linked to a mapping profile
* add an additional check whether action profile has not been linked to mapping profile and provide user-friendly message for data-import log
[MODINV-454](https://issues.folio.org/browse/MODINV-454)
> MODINV-454 - IndexOutOfBoundsException observed on Data Import (Instances Tab)

- src/main/java/org/folio/inventory/dataimport/handlers/actions/AbstractInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/InstanceUpdateDelegate.java
To update logic according to changes in [data-import-processing-core](https://github.com/folio-org/data-import-processing-core/pull/168) mapping aproach.
> MODINV-488 Update using of RecordMapper

- ramls/examples/item_get.json
- ramls/item.json
- src/main/java/org/folio/inventory/domain/items/Item.java
- src/main/java/org/folio/inventory/resources/ItemRepresentation.java
- src/main/java/org/folio/inventory/support/ItemUtil.java
- src/test/java/api/items/ItemApiExamples.java
- src/test/java/api/support/builders/ItemRequestBuilder.java
link to the ticket https://issues.folio.org/browse/MODINV-491
There was added inTransitDestinationServicePointId field in Item.json and based on it necessary changes to make possible update Items without lose that kind of information
> MODINV-491 add missing field

- pom.xml
[KAFKAWRAP-10](https://issues.folio.org/browse/KAFKAWRAP-10)
> Updated kafka-wrapper dependency

- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandlerTest.java
Block sending a requests with an empty barcode
https://issues.folio.org/browse/MODINV-508
> MODINV-508: Block sending a requests with an empty barcode

- ramls/authority.json
- ramls/samples/authority.sample
**_Purpose_**
The purpose is to get the schema of the Authority record, needed for the further mapping
**_Approach_**
Create a schema file that contains all the fields mentioned on https://wiki.folio.org/display/FOLIJET/Search+MARC+Authorities
> MODINV-504 Create schema for Authority domain object

- ramls/authority.json
**_Purpose_**
Rename property in the authority schema, the sample file is updated already
> Modinv 504 - renamed property in the authority schema

- ramls/holdings-record.json
- src/main/java/org/folio/inventory/resources/Holdings.java
Fix holdings update
* Update holdings schema with administrativeNotes fields
* Add error logging in Holdings API implementation
> MODINV-593 Fix holdings update

- descriptors/ModuleDescriptor-template.json
Resolves: https://issues.folio.org/browse/MODINV-612
> MODINV-612 Update request-storage interface version to 4.0

- README.MD
- pom.xml
- src/main/java/org/folio/inventory/MarcHridSetConsumerVerticle.java
Delete all Kafka cache occurrences
https://issues.folio.org/browse/MODDATAIMP-623
> MODDATAIMP-623. Remove Kafka cache initialization and Maven dependency

- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandlerTest.java
The mechanism for the retry in case of Optimistic locking error added for data-import flow.
This PR is just for Items. For Holdings and Instances there are another PRs.
Tests added.
> MODINV-625: (Items) Implement retry mechanism for DI update in case OL conflict.

- src/main/java/org/folio/inventory/dataimport/consumers/MarcBibInstanceHridSetKafkaHandler.java
- src/main/java/org/folio/inventory/dataimport/exceptions/OptimisticLockingException.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/AbstractInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/InstanceUpdateDelegate.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
- src/main/java/org/folio/inventory/exceptions/OptimisticLockingException.java
- src/test/java/org/folio/inventory/dataimport/consumers/MarcBibInstanceHridSetKafkaHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java
- src/test/java/org/folio/inventory/eventhandlers/UpdateInstanceQuickMarcEventHandlerTest.java
The mechanism for the retry in case of Optimistic locking error added for data-import flow. 
This PR is just for INSTANCES. For Holdings and Items will be in another PRs.
Tests added.
> MODINV-619: (Instances) Implement retry mechanism for DI update in case OL conflict.

- src/main/java/org/folio/inventory/dataimport/consumers/MarcHoldingsRecordHridSetKafkaHandler.java
- src/main/java/org/folio/inventory/dataimport/exceptions/OptimisticLockingException.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/HoldingsUpdateDelegate.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandler.java
- src/test/java/org/folio/inventory/dataimport/consumers/MarcHoldingsRecordHridSetKafkaHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandlerTest.java
- src/test/java/org/folio/inventory/eventhandlers/UpdateHoldingsQuickMarcEventHandlerTest.java
The mechanism for the retry in case of Optimistic locking error added for data-import flow.
This PR is just for Holdings. For Instance and Items there are another PRs.
Tests added.
> MODINV-624:  (Holdings) Implement retry mechanism for DI update in case OL conflict.

- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/inventory/resources/TenantApi.java
- src/main/resources/liquibase/tenant/changelog.xml
- src/main/resources/liquibase/tenant/scripts/v-18.1.0/2021-12-10--13-00-create-records-instances-table.xml
- src/main/resources/liquibase/tenant/scripts/v-18.1.0/2021-12-24--13-00-create-records-items-table.xml
- src/main/resources/liquibase/tenant/scripts/v-18.1.0/2022-01-01--13-00-create-records-holdings-table.xml
- src/main/resources/liquibase/tenant/scripts/v-18.1.0/2022-01-02--13-00-create-records-authorities-table.xml
- src/test/java/api/TenantApiTest.java
Add delete TENANT endpoint for inventory module.
Added delete TENANT endpoint and changed tenant handler version from 2.0 to 1.2.
[MODINV-630](https://issues.folio.org/browse/MODINV-630)
> MODINV-630 Add delete tenant endpoint for inventory module

- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandlerTest.java
Remove post-processing for authority update
> MODINV-639 Remove post-processing for authority update

- pom.xml
folio-kafka-wrapper v2.5.0
mod-source-record-storage-client 5.3.0
data-import-processing-core v3.3.0
> Update dependencies to release versions

- src/main/java/org/folio/inventory/DataImportConsumerVerticle.java
- src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/AbstractAuthorityEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateAuthorityEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandler.java
- src/test/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandlerTest.java
Show authority log after update
Run DI_INVENTORY_AUTHORITY_UPDATED even manualy
[MODINV-656](https://issues.folio.org/browse/MODINV-656)
> MODINV-656 Show authority log after update

- src/main/java/org/folio/inventory/dataimport/handlers/actions/HoldingsUpdateDelegate.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/InstanceUpdateDelegate.java
1. Error catching in cases when Instance+Holdings was NOT found added.
> MODINV-678: The status of SRS MARC record is not updated after uploading MARC file with non-existing instanceId in 999ff$i field.

- src/main/java/org/folio/inventory/resources/TenantApi.java
Sonar correctly reports that PreparedStatement and Liquibase are not closed in all cases in TenantApi.java:
https://sonarcloud.io/code?id=org.folio%3Amod-inventory&selected=org.folio%3Amod-inventory%3Asrc%2Fmain%2Fjava%2Forg%2Ffolio%2Finventory%2Fresources%2FTenantApi.java
Fix: Use try-with-resources to auto-close them.
> MODINV-687: Close PreparedStatement and Liquibase in TenantApi

- pom.xml
Does not change the definitions of any existing tests
> Run tests with JUnit 5

- pom.xml
- src/main/java/org/folio/inventory/DataImportConsumerVerticle.java
- src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateMarcHoldingsEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateMarcHoldingsEventHandlerTest.java
**Purpose**
Support MARC-MARC Holdings update action
JIRA: https://issues.folio.org/browse/MODINV-719
**Approach**
- Update data-import-processing-core dependency version
- Register SRS events for MARC Holdings
- Create handler for MARC Holdings update
- Add tests
> MODINV-719 Support MARC-MARC Holdings update action

- NEWS.md
- ramls/examples/instance_get.json
- ramls/examples/instances_get.json
- ramls/instance.json
- src/main/java/org/folio/inventory/domain/instances/Instance.java
- src/main/java/org/folio/inventory/resources/ItemRepresentation.java
- src/main/java/org/folio/inventory/resources/Items.java
- src/test/java/api/InstancesApiExamples.java
- src/test/java/api/items/ItemApiExamples.java
- src/test/java/org/folio/inventory/resources/ItemRepresentationTest.java
*Scope*
Remove the experimental Dublin Core support that was implemented a long long time ago (in a project far far far away).
> Remove self links from instances and items MODINV-734

- pom.xml
- src/main/java/org/folio/inventory/InventoryVerticle.java
- src/main/java/org/folio/inventory/resources/AdminApi.java
- src/test/java/api/AdminApiTest.java
- src/test/java/api/ApiTestSuite.java
- src/test/java/api/support/ApiRoot.java
- src/test/java/it/InventoryIT.java
https://wiki.folio.org/display/DD/Back+End+Module+Health+Check+Protocol requires /admin/health to return status code 200 (if healthy) for all back-end modules.
> MODINV-749: Add /admin/health

- src/main/java/org/folio/inventory/resources/Items.java
- src/test/java/api/BoundWithTests.java
- Partitions the request for referenced holdings and instances, using MultipleRecordsFetchClient.
> Support "unlimited" bound-with parts in GET item by ID (MODINV-752)

- pom.xml
https://issues.folio.org/browse/ISBNUTIL-14
> [ISBNUTIL-14]Update ISBNUTIL dependency

- src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
- src/main/java/org/folio/inventory/dataimport/consumers/QuickMarcKafkaHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/AbstractAuthorityEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/AuthorityUpdateDelegate.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateHoldingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateMarcHoldingsEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/DeleteAuthorityEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/HoldingsUpdateDelegate.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/InstanceUpdateDelegate.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/MarcBibMatchedPostProcessingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/PrecedingSucceedingTitlesHelper.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateMarcHoldingsEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/AbstractMatchEventHandler.java
- src/main/java/org/folio/inventory/dataimport/util/LoggerUtil.java
In the task [MODINVSTOR-866](https://issues.folio.org/browse/MODINVSTOR-866) we met situation with specific DI behavior on the one Villanova test env. We couldn't reproduce this case on the other hosted and local envs. Current INFO log messages have not allowed us to understand the main reason of this situation. We need to improve code coverage by log messages for the INFO level for all modules of DI.
> [MODINV-627]Improving code coverage by log messages for the INFO level

- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
- src/main/java/org/folio/inventory/domain/items/CirculationNote.java
Added validation for 'Check in note' and 'Check out note' values for circulation note type
Jira: https://issues.folio.org/browse/MODINV-755
> [MODINV-755] Added validation for circulation note type

- src/main/java/org/folio/inventory/dataimport/handlers/actions/AuthorityUpdateDelegate.java
- src/test/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandlerTest.java
After updating, record contains old values 
- Instead of merging full records. Just take version from existed record 
https://issues.folio.org/browse/MODINV-771
> MODINV-771 Additional "Authorized" record appears after user edits "1XX" MARC tag

- src/main/resources/log4j2-json.properties
- src/main/resources/log4j2.properties
https://issues.folio.org/browse/MODDATAIMP-758
> [MODDATAIMP-758]Imrove logging (hide SQL requests)

- src/main/java/org/folio/inventory/domain/instances/AlternativeTitle.java
- src/main/java/org/folio/inventory/domain/instances/Authorized.java
- src/main/java/org/folio/inventory/domain/instances/Contributor.java
- src/main/java/org/folio/inventory/domain/instances/SeriesItem.java
- src/main/java/org/folio/inventory/domain/instances/Subject.java
- src/test/java/api/support/InstanceSamples.java
Add authorityId to AlternativeTitle object
> MODINV-775 Add authorityId to AlternativeTitle object

- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandlerTest.java
Set POLine id when Item is created by DI
Added logic, that sets poLineId for the item if PO_LINE event exists in the payload
> [MODINV-774] Set POLine id when Item is created by DI

- src/main/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandler.java
- src/test/java/org/folio/inventory/dataimport/consumers/MarcBibUpdateKafkaHandlerTest.java
Exclude nameSpace from links.instance-authority-stats event
> MODINV-775 Exclude nameSpace from links.instance-authority-stats event

- pom.xml
Update folio-isbn-util to 1.5.0
> [ISBNUTIL-18] Update folio-isbn-util to 1.5.0

- src/main/java/org/folio/inventory/dataimport/services/OrderHelperServiceImpl.java
- src/test/java/org/folio/inventory/dataimport/services/OrderHelperServiceTest.java
to be able to send event for triggering order opening processing
[MODORDERS-808](https://issues.folio.org/browse/MODORDERS-808)
> MODORDERS-808 - Adjusted payload preparation for initialization order opening processing

- pom.xml
Updated data-import-processing-core dependency
> [MODDICORE-306] Update data-import-processing-core dependency

- src/main/java/org/folio/inventory/common/dao/EntityIdStorageDaoImpl.java
Fix Type Mismatch Error on record_id column in db log
cast **record_id** to uuid
Jira: https://issues.folio.org/browse/MODINV-778
> [MODINV-778] Fix Type Mismatch Error on record_id column in db log

- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateMarcHoldingsEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateAuthorityEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateMarcHoldingsEventHandlerTest.java
to prevent import job from being hanged during import records for MARC-Authority/MARC-Holdings update if an incoming record contains authorityId/holdingId that is not associated with the existing one.
* add check that the corresponding authority/holding has not been found by specified Id and fail result `promise` with appropriate message so that it would be reflected in the log
* add tests
[MODINV-783](https://issues.folio.org/browse/MODINV-783)
> MODINV-783 - Update job stuck while updating records with invalid external id

- pom.xml
> [MODDICORE-304]Update data-import-processing-core dependency

- descriptors/ModuleDescriptor-template.json
> MODINV-798 Update instance-authority-links dependency interface version

- src/main/java/org/folio/inventory/domain/AsynchronousCollection.java
- src/main/java/org/folio/inventory/exceptions/AbstractInventoryException.java
- src/main/java/org/folio/inventory/exceptions/ExternalResourceFetchException.java
- src/main/java/org/folio/inventory/exceptions/InternalServerErrorException.java
- src/main/java/org/folio/inventory/resources/Instances.java
- src/main/java/org/folio/inventory/support/EndpointFailureHandler.java
- src/test/java/api/InstancesApiExamples.java
Changed behavior of creating instance to properly handle ValidationException
> MODINV-800  Unify API response in case of ValidationException (http 422)

- descriptors/ModuleDescriptor-template.json
- src/test/java/api/support/dto/Request.java
- src/test/java/support/fakes/FakeOkapi.java
- fix the spelling of the 'fulfillmentPreference' field;
- increase the 'request-storage' interface version to 6.0;
Resolves: [MODINV-808](https://issues.folio.org/browse/MODINV-808)
> MODINV-808 Update request-storage interface version

- src/main/java/org/folio/inventory/resources/ItemsByHoldingsRecordId.java
- src/test/java/api/BoundWithTests.java
https://issues.folio.org/browse/MODINV-829
> MODINV-829: /items-by-holdings-id fails when there is a large number of items

- NEWS.md
- src/main/java/org/folio/inventory/DataImportConsumerVerticle.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandlerTest.java
Resolves: [MODINV-842](https://issues.folio.org/browse/MODINV-842) Data Import 3rd update Action on Item Record Fails
> [MODINV-842] Data Import 3rd update Action on Item Record Fails

- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/ItemLoader.java
- src/test/java/org/folio/inventory/eventhandlers/MatchItemEventHandlerUnitTest.java
[MODINV-862](https://issues.folio.org/browse/MODINV-862) propblem 2.
**Depends on PR:** https://github.com/folio-org/data-import-processing-core/pull/305.
**Description:**  deserialize multiple holdings as an array.
> MODINV-862: Deserialize multiple holdings as an array

- src/main/java/org/folio/inventory/dataimport/handlers/matching/loaders/ItemLoader.java
- src/test/java/org/folio/inventory/eventhandlers/MatchItemEventHandlerUnitTest.java
**Description:** fix index out of range exception according to Karate tests.
Tested on **rancher** and explored logs after testing:
> MODINV-862: Fix index out of range exception according to Karate tests

- src/main/java/org/folio/inventory/consortium/consumers/ConsortiumInstanceSharingHandler.java
- src/main/java/org/folio/inventory/consortium/model/SharingInstance.java
- src/test/java/org/folio/inventory/dataimport/consumers/ConsortiumInstanceSharingHandlerTest.java
Refactor and add tests for Instance sharing functionality
Test coverage was completed. Code review will be closed in scope of [MODINV-821](https://issues.folio.org/browse/MODINV-821) because I faced with "callback hell".
[MODINV-870](https://issues.folio.org/browse/MODINV-870)
> MODINV-870: Refactor and add tests for Instance sharing functionality

- src/main/java/org/folio/inventory/dataimport/handlers/actions/AuthorityUpdateDelegate.java
Populate source field in AuthorityUpdateDelegate with `MARC` value
> MODINV-878 Populate source field in AuthorityUpdateDelegate

- src/main/java/org/folio/inventory/consortium/handlers/FolioInstanceSharingHandlerImpl.java
- src/main/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImpl.java
- src/test/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImplTest.java
[MODINV-877](https://issues.folio.org/browse/MODINV-877) Adjust assignment of Instance HRID
Fixed issue: update hrid for local instance when it's shared to consortium
> MODINV-877 update hrid for local instance when it's shared to consortium

- src/test/java/org/folio/inventory/consortium/consumers/ConsortiumInstanceSharingHandlerTest.java
- src/test/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImplTest.java
Update unit tests for [MODINV-877](https://issues.folio.org/browse/MODINV-877)
> MODINV-877 update unit tests

- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
- src/test/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandlerTest.java
Just minor tests changes to fix the build.
> MODINV-860: Build fixed.

- NEWS.md
- src/main/java/org/folio/inventory/DataImportConsumerVerticle.java
- src/test/java/org/folio/inventory/dataimport/consumers/DataImportConsumerVerticleTest.java
- src/test/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateHoldingEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/MarcBibModifiedPostProcessingEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandlerTest.java
- src/test/java/org/folio/inventory/eventhandlers/MatchHoldingEventHandlerUnitTest.java
- src/test/java/org/folio/inventory/eventhandlers/MatchInstanceEventHandlerUnitTest.java
- src/test/java/org/folio/inventory/eventhandlers/MatchItemEventHandlerUnitTest.java
**Jira:**  [MODSOURMAN-1022](https://issues.folio.org/browse/MODSOURMAN-1022)
**Purpose:** Remove step of initial saving of incoming records to SRS
> MODSOURMAN-1022: migrate from DI_SRS_MARC_BIB_RECORD_CREATED to DI_INCOMING_MARC_BIB_RECORD_PARSED event

- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateItemEventHandlerTest.java
Throw an exception if the user tries to create multiple Items with different material types during order creation
Validate items that contains PO_LINE at context to have same material type
> [MODINV-928] Throw an exception if user tries to create multiple Items with different material types during order creation

- NEWS.md
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtil.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtilTest.java
[MODINV-921](https://issues.folio.org/browse/MODINV-921)
Apply 005 logic before saving MARC Bib in SRS
Added functionality to apply the 005 field logic and reset the updated record in the payload context.
> MODINV-921: Apply 005 logic before saving MARC Bib in SRS

- src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtil.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtilTest.java
- src/test/resources/marc/parsedMarcRecord.json
1. Added 001+003->035 fields logic before mapping the Instance
2. populate 001 and 999 ff i fields after Instance is saved
3. add POST request to mod-srs to save MARC record
> MODINV-849: Add 001+003->035 fields logic before mapping the Instance

- src/main/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImpl.java
- src/test/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImplTest.java
to fix issue when a local MARC source instance is shared, any instance info that is not controlled by the underlying MARC is absent in the shared instance
* perform an update of the shared Instance with only non-MARC controlled fields from the original local instance after the shared instance has been created
* add test
[MODINV-929](https://issues.folio.org/browse/MODINV-929)
> MODINV-929 - Consortial: non-MARC data not saved when local source = MARC instance is promoted

- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtil.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
**Purpose:** set external IDs before Record creation in SRS
**Before:** 
**After:**
> MODDATAIMP-957: set external IDs before Record creation in SRS

- src/main/java/org/folio/inventory/dataimport/handlers/matching/preloaders/OrdersPreloaderHelper.java
- src/test/java/org/folio/inventory/eventhandlers/preloaders/OrdersPreloaderHelperTest.java
Preload orders not only with status Open
Remove condition on status Open from preload cql
> [MODINV-876] Preload orders not only with status Open

- src/main/java/org/folio/inventory/dataimport/handlers/matching/AbstractMatchEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/preloaders/AbstractPreloader.java
- src/main/java/org/folio/inventory/dataimport/handlers/matching/util/EventHandlingUtil.java
- src/test/java/org/folio/inventory/eventhandlers/MatchInstanceEventHandlerUnitTest.java
Import of .mrc files with match on POL/VRN stuck in DI 
Not match on central tenant by POL or VRN during consortia process
> [MODINV-952] Not match on central tenant by POL or VRN during consortia process

- src/main/java/org/folio/inventory/domain/items/Item.java
- src/main/java/org/folio/inventory/resources/ItemRepresentation.java
- src/main/java/org/folio/inventory/support/ItemUtil.java
Previously we update item.json schema in scope of this PR: https://github.com/folio-org/mod-inventory/pull/673/files 
and now update java code for it
Purpose:
https://issues.folio.org/browse/MODINV-959
> [MODINV-959] Add new field "Display summary" for the item schema

- src/main/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtil.java
Fix karate tests
Handle IndexArrayOutofBounds exception when deciding to update field 005 by checking if the list is empty before getting the first item.
> FAT-9178 fix exception when deciding to update Field 005

- src/main/java/org/folio/inventory/dataimport/handlers/actions/AbstractInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/CreateInstanceEventHandlerTest.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java
Send request on central tenant srs during instance update if needed
Send request on central tenant srs during instance update
> [MODINV-972] Send request on central tenant srs during instance update if needed

- src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateHoldingEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateItemEventHandler.java
- src/main/java/org/folio/inventory/dataimport/handlers/actions/UpdateMarcHoldingsEventHandler.java
- src/main/java/org/folio/inventory/dataimport/util/LoggerUtil.java
Add incomingRecordId to logs
Add incomingRecordId to logs
> [MODSOURMAN-1141] Add incomingRecordId to logs

- NEWS.md
- pom.xml
Upgrade mod-inventory to Vertx 4.5.4
[MODDICORE-398](https://folio-org.atlassian.net/browse/MODDICORE-398)
> MODDICORE-398: Upgrade vertx to 4.5.4

- NEWS.md
- descriptors/ModuleDescriptor-template.json
Update holdings-storage API from 6.0 to 7.0
> MODINV-1043 Update holdings-storage API version

- src/main/java/org/folio/inventory/resources/UpdateOwnershipApi.java
- src/test/java/api/holdings/HoldingsUpdateOwnershipApiTest.java
- src/test/java/support/fakes/FakeStorageModule.java
- src/test/java/support/fakes/processors/RecordPreProcessor.java
- src/test/java/support/fakes/processors/StorageConstraintsProcessors.java
- src/test/java/support/fakes/processors/StorageRecordPreProcessors.java
Assign new ids for holdings/items on target tenant during update ownership of holdings
Created new classes for storage of old ids to make it possible to delete old entities
> [MODINV-1053] Handle assignment of ids during update ownership of holdings

- src/main/java/org/folio/inventory/dataimport/util/AdditionalFieldsUtil.java
Fix vulnerability related to AdditionalFieldsUtil class
[MODINV-1058](https://folio-org.atlassian.net/browse/MODINV-1058)
> MODINV-1058 Fix vulnerability in AdditionalFieldsUtil class

- src/main/java/org/folio/inventory/dataimport/handlers/matching/AbstractMarcMatchEventHandler.java
Enhance implementation of /source-storage/records/matching endpoint to account for comparison part when building a search query to get the record for matching.
NPE was found 
Fix NPE.
> MODSOURCE-787: fix NPE

- src/main/java/org/folio/inventory/resources/Instances.java
Adding temporary logging to investigate 422 error issue when editing instances in bulk edit on snapshot environment
> Logging improvements

- src/main/java/org/folio/inventory/resources/Instances.java
Reverts folio-org/mod-inventory#772
> Revert "Logging improvements"

- src/main/java/org/folio/inventory/dataimport/consumers/DataImportKafkaHandler.java
[MODDATAIMP-1065](https://folio-org.atlassian.net/browse/MODDATAIMP-1065) The imported file is displayed in the 'Running' section even it has been imported and displayed in the logs
> MODDATAIMP-1065 The imported file is displayed in the 'Running' section even it has been imported and displayed in the logs

- ramls/instance.json
Updating instances.json schema.
> Instance.json schema improved.

- src/main/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImpl.java
- src/test/java/org/folio/inventory/consortium/handlers/MarcInstanceSharingHandlerImplTest.java
suppressFromDiscovery value is not synchronized between member and centrlal tenants
Update suppress from discovery flag at SRS record during instance sharing
> [MODINV-1123] Update suppress from discovery flag at SRS record during instance sharing

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleInstanceCollection.java
- src/test/java/support/fakes/FakeOkapi.java
JIRA: https://folio-org.atlassian.net/browse/MODINV-1101
> MODINV-1101: Replace usage of deprecated instance-storage-batch API

- src/main/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandler.java
- src/test/java/org/folio/inventory/dataimport/handlers/actions/ReplaceInstanceEventHandlerTest.java
Overlay of Instance does not fix record without ACTUAL state
Create record during instance update if it does not exist
https://folio-org.atlassian.net/browse/MODSOURCE-867
> [MODSOURCE-867] Allow update of instance without related Marc record

- src/main/java/org/folio/inventory/domain/instances/Dates.java
- src/main/java/org/folio/inventory/domain/instances/Instance.java
- src/test/java/org/folio/inventory/domain/instances/DatesTest.java
JIRA: https://folio-org.atlassian.net/browse/MODINV-1186
> MODINV-1186: Updating MARC bib record removes Date 1, Date 2 and Date type fields

- src/main/java/org/folio/inventory/instanceingress/handler/InstanceIngressEventHandler.java
- src/test/java/org/folio/inventory/instanceingress/handler/CreateInstanceIngressEventHandlerUnitTest.java
- src/test/java/org/folio/inventory/instanceingress/handler/UpdateInstanceIngressEventHandlerUnitTest.java
Merge the changes made to v21.1.3 to master branch.
> MODINV-1205: Use tenant specific cache for MappingMetadata

- NEWS.md
- src/main/java/org/folio/inventory/storage/external/ExternalStorageModuleCollection.java
Adding mechanism to NOT add  "X-Okapi-User-Id" header, if it is blank.
> MODINV-1189: Error editing the "Temporary" field in the holding

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODINV-1239
> Release v21.1.7

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/item.json
- src/main/java/org/folio/inventory/domain/items/Item.java
- src/main/java/org/folio/inventory/resources/ItemRepresentation.java
- src/main/java/org/folio/inventory/support/ItemUtil.java
Addition of the order field to the existing item APIs
https://folio-org.atlassian.net/browse/MODINV-1249
- update API definition
- update interface versions
- modify DTO converters
> MODINV-1249 Addition of the order field to the existing item APIs

- src/main/java/org/folio/inventory/resources/UpdateOwnershipApi.java
The field must be filled in without changes.
> MODINV-1266: Fix order field behavior
